### ISSUE TITLE
New Feature: Bundle Products

### ISSUE THREAD

**Issue by b-schweiger** [pretix/pretix#1001]
We would like to be able to offer bundle products, for example "Two Tickets plus a hotel room" for a discounted price. Right now, we do that by creating a seperate product. The ticket for this product serves as a voucher to get the parts upon checkin. That requires lots of manual steps. 
A bundle product (or maybe call it meta product) feature, where you could configure "Product consists of 2 times product x plus 1 product y" would be perfect. Buying the bundle should result in all the tickets for the parts being printed.

**Comment by raphaelm** [comment]
If it were only one ticket + hotel room, my suggestion would be to create a product that you just call "ticket + hotel room" and that you add it to both quotas and both check-in lists: Both our quota handling and our checkin logic is more than flexible enough for that. But it stops working at "two tickets", since that would at least need to subtract 2 from the quota and do other magical things at check-in.

The current plan was to allow to add a "quota multiplicator" at some point to implement group tickets (#433), but I like the idea of bundles even more. This would solve your problem and the problem of group tickets at once.

I'm not yet 100% sure how we should implement it. Probably those bundles should be ordinary products with all their features (availability timeframe, pricing, quotas, …), but that automatically add all their "contained products" as sub-products to the cart. We could maybe even re-use the mechanism and data structure for add-on products for some parts.

This really sounds interesting.

Are you interested in developing this feature yourself? If not, are you commercially interested in this feature and willing to sponsor development on it?

**Comment by b-schweiger** [comment]
It sure would be exciting to develop that myself. However, I lack a) the time required to get up to speed with the whole project and b) the python skills required (which could be remedied by more time, see a). 
Since we're not making any profits of our events, our IT budget is very limited. I can talk to my partners. Where can I reach you to discuss sponsoring more privately?

**Comment by raphaelm** [comment]
> Since we're not making any profits of our events, our IT budget is very limited. I can talk to my partners. Where can I reach you to discuss sponsoring more privately?

Just reach out to sales@pretix.eu, and we can see what's possible :)

**Comment by raphaelm** [comment]
Hmm, okay, that's really a different story, so we'd probably keep this ticket for the bundles, as suggested by @b-schweiger, and #433 for your use case.
