### ISSUE TITLE
Mailing list/chatroom for new contributors? 

### ISSUE THREAD

**Issue by R9295** [pretix/pretix#1002]
Hey, 

Pretix seems like a cool project and I'd like contribute. I'm creating an issue as I don't see a platform used for communication like https://gitter.im or IRC as I'd like to possibly introduce myself and see where I can get started. I've been through the setup docs, etc.

**Comment by raphaelm** [comment]
Hi Aarnav, thanks for making contact and great that you want to get involved! :) We currently do not have a channel like that, mainly because there are not that many people involved in contributing to pretix over a longer timeframe and I don't have the capacity to monitor an IRC channel to give help all day, for me it's much easier to answer to a bulk of issues and emails from time to time since it's less interruptive. So let's keep this issue open to see if more people think this would be a good idea, and until then, just ask your questions here on GitHub :)
