### ISSUE TITLE
API 403 on missing/not-found resource is surprising/misleading

### ISSUE THREAD

**Issue by thegcat** [pretix/pretix#1014]
When querying for [question options using the API](https://docs.pretix.eu/en/latest/api/resources/question_options.html#get--api-v1-organizers-(organizer)-events-(event)-questions-(question)-options-) I received a 403 error (`{"detail":"Du hast keine Berechtigung, um diese Aktion durchzuf\u00fchren."}`) while looking for the options of an existing question in a non-existing event (I got the event slug wrong, the organiser slug and the question ID were correct).

This is misleading and should be responded with a [404](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404). I have no strong opinion whether the detailed error message should be "we can't find what you're looking for" or "we can't find the Event you are referring to" though.

(Yes, I am aware that the API docs document that 403 might also mean "we can't find some parent resource", it is still misleading and I would argue not spec-conform. A whole other issue would be why the organiser and event slugs need to be part of the URL, but that's not the moat I'm willing to die on tonight :-) )

**Comment by raphaelm** [comment]
> This is misleading and should be responded with a 404. I have no strong opinion whether the detailed error message should be "we can't find what you're looking for" or "we can't find the Event you are referring to" though.

Hmm, yes, we could opt for 404 as well, but then we'd also need to return 404 for events that exist, but you don't have permission to. Either way, we need to violate the spec one way or another, since we can't disclose whether events exist or not if you do not have access.

I'm not sure if it is reasonable to assume that people rely on this and if we should change this now.

> A whole other issue would be why the organiser and event slugs need to be part of the URL

To save you from making horrible mistakes and keep everything contained ;)

**Comment by thegcat** [comment]
> To save you from making horrible mistakes 

Well, as most interaction would probably be through some client app I don't see the point, and my experience so far has been that tying API design to the current content/db structure leads to pain down the road more often than not.

I haven't looked at your Plugin API, but I would wager you don't require the organiser and event slugs to query and interact with a question?

(and last but not least I'd wager using HATEOS or at least "rel" and so on links would alleviate the need to construct the URLs "by hand" and thus reduce the possibility of errors, but that's just a hunch)

> and keep everything contained ;)

Well, I see the internal structure unnecessarily bleeding into the API thus being less contained, but oh well 😊

Anyway, as I said keep at least the 403/404 distinction in mind for future API design, thank you for taking the time to shed some light of the points I proposed discussing and generally for your collective work on Pretix.

**Comment by raphaelm** [comment]
> Well, as most interaction would probably be through some client app I don't see the point, and my experience so far has been that tying API design to the current content/db structure leads to pain down the road more often than not.

Events in pretix are heavily isolated and there is no cross-talk between questions/items/order/… in separate events, ever. This is also unlikely to change, since it's a very fundamental part of pretix' database design. Nothing is impossible, but for the forseeable future, there's no reason to assume otherwise.

Development of client applications get's a lot easier this way, since for most applications you can just have ``pretix.eu/api/v1/organizers/…/events/…/`` as your configurable API endpoint and can access all sub resources, without *ever* caring to check that objects belong to the correct event, etc.

For most things a client application is concerned with, an organizer (and for most things, an event as well) can be considered as a separate database of things.

Therefore, I still stay behind the API design of implementing this as nested resources.

> I haven't looked at your Plugin API, but I would wager you don't require the organiser and event slugs to query and interact with a question?

If you want to interact with a question as a plugin, you work directly on Django's database level, so that's up to you. It's certainly recommended to use code patterns like ``event.questions.get(…)`` to avoid accidental data access across events. Since a plugin can run any Python code, there's little point in requiring.
