### ISSUE TITLE
Allow sending mails using the system mailer

### ISSUE THREAD

**Issue by DerDakon** [pretix/pretix#1022]
I would like to send mails using the system mailer, which knows e.g. which relay to use and which IP address to bind to when sending.

**Comment by raphaelm** [comment]
Django only supports sending mails via SMTP, and we won't to the extra complexity on adding something else on our own, sorry.

**Comment by DerDakon** [comment]
Then I would like a way to set at least the outgoing IP.

**Comment by raphaelm** [comment]
Apparently, Python 3.3+ indeed has a [source_address](https://docs.python.org/3/library/smtplib.html?highlight=smtp#smtplib.SMTP) parameter in the ``smtplib`` module, but [Django](https://docs.djangoproject.com/en/2.1/topics/email/#smtp-backend) doesn't seem to support it. Feel free to open a feature request in [Django's bug tracker](https://code.djangoproject.com/).

Since in my experience this is a rather exotic requirement, I don't see it justified that pretix ships a custom implementation of the SMTP backend for this.
