### ISSUE TITLE
Download as "attachment" vs "inline"

### ISSUE THREAD

**Issue by ahus1** [pretix/pretix#1036]
Whenever I download a PDF ticket or contents a user uploaded during checkout (as part of the questions), the browser opens the "save as" dialog. I suppose this due to the "Content-Disposition" set to "attachment".

Other checkout systems seems to open PDFs and images often "inline", that is in a full-page browser window.

At least in the two situations described above (PDF ticket and reviewing user uploaded content) it would be nice to have the content directly viewable, that is: inline. 

What do you think?

**Comment by raphaelm** [comment]
This is set on purpose, at the moment.

For security reasons, pretix sets rather strict ``Content-Security-Policy`` headers. With those headers, the inline PDF viewer of most browsers breaks -- which can be fixed for Chrome and Firefox, but is not fixable for Safari. Omitting the CSP headers seems to come with it's own risks, i.e. in case of an exploit for PDF.js embedded in the PDF file, since event organizers can control the PDF file to a large extend.
