### ISSUE TITLE
Bug: Orders By Date shows wrong value

### ISSUE THREAD

**Issue by genofire** [pretix/pretix#1045]
There is **one Order** with **three Places**, which is shown in _Orders By Products_ correct

![screenshot from 2018-10-13 12-56-58](https://user-images.githubusercontent.com/6905586/46904634-dcf27300-ced6-11e8-9031-20ba36fe4a15.png)

**Comment by raphaelm** [comment]
There's really still *just* one order? It really is confusing how it thanges to the right of the cart and I can't explain the 5 below, either. This is weird.

**Comment by raphaelm** [comment]
Ah. No, sorry, then it's just a misunderstanding and the graphs are correct.

The first graphs shows the number of orders created on a date, so it shows a one on three dates and zero otherwise. It looks clearer once the graph is longer, i.e. times are no longer shown.

The second graph shows number of sold products, which is correct as well.

**Comment by genofire** [comment]
Then please change to 'Order by Date' to 'Places by Date'.
(Or change the Tooltip text)
