### ISSUE TITLE
PDF Editor: Allow to rotate text fields

### ISSUE THREAD

**Issue by genofire** [pretix/pretix#1053]
Allow the Text to rotate

**Comment by raphaelm** [comment]
Hi,

we initially decided against this since it's a very complex operation (which point to rotate around? how to handle multi-line text?), and we need to implement all of these operations in at least three different rendering engines and – that's the hard part – make sure they look the same:

* HTML canvas for our preview
* reportlab for rendering the actual PDFs
* Java/iText for pretixPOS/pretixSCAN

Therefore, it's always a bit of an effort to add these things.

That said, it would most certainly be useful and I'd love to have it!
