### ISSUE TITLE
Add insufficient payment option

### ISSUE THREAD

**Issue by agowa338** [pretix/pretix#1065]
There should be a "insufficient payment" option when manually marking orders as paid and Pretix should than send automatically an E-Mail informing the attendee of the insufficient payment.
Example mail text:
```plain
Hello {invoice_name},

Your Payment for the event {event} is not sufficient, you have only payed {payment_received_amount} instead of {order_total}. Please Transfer {payment_missing_amount} within the next three days. If no payment is received, your order may be invalidated and any partial payment will be refunded.

You can change your order details and view the status of your order at
{url}

Best regards,
Your {event} team
```
Therefore also three new variables would be required:

- payment_received_amount: The amount received.
- order_total: The total amount that should be paid.
- payment_missing_amount: The outstanding amount that needs to be payed.

**Comment by raphaelm** [comment]
I'm not sure if we really need this. I try to avoid adding new email templates, since this makes configuring an event harder every time. Also, with pretix 2.0+, partial payments are supported and an order with insufficient payment will just be kept unpaid and payment reminders will be triggered. If the user visits the order detail page, it will show the amount still missing.
