### ISSUE TITLE
add-on with negative price displayed not nice

### ISSUE THREAD

**Issue by j-herden** [pretix/pretix#1090]
There is an assumption that the price of an add-on is positive. We want to have a discount, but this is shown with an extra plus sign. 
See screenshot:
![grafik](https://user-images.githubusercontent.com/2026587/48618239-0c464500-e999-11e8-8774-8778edb5fa4f.png)

**Comment by raphaelm** [comment]
That's unfortunately not that easy to fix, since the full string format, e.g. ``{name} (+ {price} plus {taxes}% {taxname})`` is part of the translation file and we'd need to add duplicate strings for the translators to make this happen. I'll keep the issue open since it is a problem, but negative prices are not a usage pattern we encourage and therefore does not have a very high priority to us.

**Comment by j-herden** [comment]
I do not see the need to duplicate strings for the translators here.
You may remove the '+' from your translation string and format the {price} in a way that the sign is displayed too.

**Comment by raphaelm** [comment]
Should be resolved by the new add-on step implementation
