### ISSUE TITLE
Managed bookings / Grouptickets

### ISSUE THREAD

**Issue by bockstaller** [pretix/pretix#1092]
Currently only the a customers themself or eventstaff can modify and manage a booking. This is sufficient for all events without a third part managing bookings for a group of customers.

Presenting companies may want to offer sponsored tickets for key customers and buy tickets for their own booth personnel too. A similiar usecase is the registration for a youth camp with many different participating groups which are managed by their local leaders.

In both cases the third party has legitimate reasons to access their customers/participants information.
A company would like to know who has accepted their offer, in order to organize meetings during the fair or follow up on a lead. The leaders of the youth group need a complete list of their participants to organize the trip to the camp.

## Features

* The third party can enter a custom price (sponsored by XY/additional travel costs for the youth group) and payment options (free/bank account).
* They can invite customers/participants to register themself by handing them a token or register them directly (with an option for opt-in by the customer).
* They are able to see and modify the ticket details entered by their customers, make comments, mark them (internally) as paid and export this information.
* All tickets managed by this third party are billed to them.

### 1. Duplicate the event and give the third party a team account with the rights to modify and create bookings.

__Pros__:

* works nearly out of the box
* easily customizable shops and individual pricing free/surcharge

__Cons__:

* the organizer has no unified view on all bookings
* no global quota enforcement
* Checkin must support many different events
* no group billing (adding up all orders for a group event)
* feels like a realy dirty hack

### 1. Create a plugin implementing the mentioned behaviour.

__Pros__:

* organizer has all tickets in one event
* all functions can be implemented as desired

__Cons__:

* the plugin would interact heavily with core features of pretix (at least the ticketshop and billing logic). I have the feeling that this would lead to quite brittle solution

### 2. Implement this behaviour in pretix core.

__Pros__:

* as above

__Cons__:

* more logic to maintain in pretix core

@raphaelm What is your opinion on this topic? Is it a featureset that is interesting for pretix as a project or is it to specific?

**Comment by raphaelm** [comment]
Hi,

thanks for the input! We have an idea on our internal roadmap, far ahead in the future, that does *some* of this, but doesn't even come close: As part of a "trade fair module", we'd enable exhibitors to a custom backend where they can

* generate tickets for their booth staff
* generate vouchers for customers they'd like to invite
* see registration data of people registered with these vouchers

This would probably be implemented as a plugin as part of pretix Enterprise/Hosted. But as I said, we haven't planned this out in more specific terms yet.

However, what you're asking for is much more. Having those sub-groups set up their own pricing, payment methods and then billing them for the tickets by bulk would ne *much* more complicated. We'd need separate sets of product an payment settings per event, with a much more fine-grained permission system to access them. To be honest, I absolutely see this out of scope for pretix core, since it will introduce a *lot* of complexity for a very specific use case. The only way I see this happening would be to have separate events, deal with quotas and billing manually and synchronize ticket codes into the main event through a plugin or the API to make check-in work.

**Comment by raphaelm** [comment]
Closing this for now to keep the issue tracker manageable, feel free to reopen if you see fit.
