### ISSUE TITLE
Event series: Consider series-level presale timeframe

### ISSUE THREAD

**Issue by felixrindt** [pretix/pretix#1110]
With subevents, only the presale period of the subevent itself is checked, not the one configured in the main event settings. We could check for both, e.g. by overwriting

https://github.com/pretix/pretix/blob/478d8e4116956cc72090d514ed222a42e70d27b0/src/pretix/base/models/event.py#L129

A subevent presale would be running, if it's own presale start date is passed and the overall presale start is passed. (Similar for presale end). Alternatively, if a subevent doesn't have a presale period considered, the overall settings could be inherited.

This could be useful for users who want to start the presale for all of their subevents at the same time. They could then only change one setting instead of having to go through each subevent one by one.

**Comment by raphaelm** [comment]
Hmm, I see the point for the start date. On the other hand, this makes it easy enough for users to "screw up", i.e. have their ticket shops (un)available without intention.

I'd rather consider just not having the option in the main settings for event series (when it is ignored anyways). Not ignoring it is also kinda confusing since we ignore the "event date start/end" in sub-events already, even though we show the fields.

**Comment by felixrindt** [comment]
Seems like there actually is a check, it's just not visible through the indicator pills in the subevent list. 

Anyway, I think removing settings is a good thing, although I would like a way to control the presale start for the whole series.

**Comment by raphaelm** [comment]
Fixed by #1851
