### ISSUE TITLE
bug: locale mixup when using "view order as user" from backend + other locale inconsistencies

### ISSUE THREAD

**Issue by Zambiorix** [pretix/pretix#1176]
- Set backend locale to english for logged-in admin account
- Show order details
- "View order as user" (separate window with order pops up)
- Issue: The order should be shown in the locale of the order: it is not, unless that locale is accidentally the same as the current backend locale
- Change the locale (as user)
- Go back to the backend and refresh
- Issue: The backend shows the locale of the order (and ignores the locale of the logged-in admin)
- Issue: The locale for that order is not updated to the user's new preference
- Issue: The PDF ticket download for the user does not honour the locale change, neither from the backend or the "View order as user" page

- Change the order locale from the backend, 
- Issue: when the user opens his order link again, that change is not visible
- Issue: in that case, the ticket PDF does not honour the changed locale, neither from the backend or the "View order as user" page

IMHO, there should be separate session information (at least for locales) for backend pages and order-link pages (shouldn't the order-link pages always be seen "as user" ?)

There also should be a strict sync between "order-locale" on the backend, the ticket-PDF locale, and locale preference of the user on his order-link page.

**Comment by raphaelm** [comment]
To boil it down, there are two issues here:

* Frontend and backend locale are coupled in weird ways. This is known (see #212) and we should do something about it (I might have a short look later).

* Order pages are currently not dependent on "order locale", and I'm not sure it's a good idea to change that since it involves turning the stack upside down (the locale is chosen long before the order is fetched from the database). I don't think that's necessary either, since when users click the link to the order page we have other information to determine the locale from, such as their browser language or previous session cookie. We just need the order locale for situations where we do not have that information, such as when sending emails or generating tickets. I'd consider this a wontfix.

As for the PDFs, PDFs are always generated in the order locale. Also, PDFs are cached and the cache is not invalidated when the order locale is changed, as far as I can see. I don'T consider that critial.

**Comment by Zambiorix** [comment]
I still consider the non-sync of order locale and user's change of that on the order-link pages an issue.
If the user can only set the language (automatically by browser preference, or manually by selecting language link) then that language selection on the order-link page should not be there anymore. And the order-link page should always be in the language of the order. If not, that will cause confusion. 

I am preparing Pretix for a large event, with lots of international users (23 countries last year) and I am absolutely certain that our backend folks will get questions about that behaviour.

Also, the missing PDF cache invalidate on order locale change is what it is: a bug
Why not mark this issue as a bug?

I am aware that we are not paying customers (that is not my choice), but I proposed the use of Pretix to our organisation because I think it is a great system. And because we are not paying customers, I consider it my absolute duty to inform you about all the issues I encounter and all the enhancements that could be useful to us and to others. So you can make an already great system even better.

Now I have the impression that my feedback is not taken seriously and that you avoid marking bugs as bugs for not showing too much red on the front page?

I hope I am wrong.

**Comment by raphaelm** [comment]
> I still consider the non-sync of order locale and user's change of that on the order-link pages an issue.
> If the user can only set the language (automatically by browser preference, or manually by selecting language link) then that language selection on the order-link page should not be there anymore. And the order-link page should always be in the language of the order. If not, that will cause confusion.

Even though, I don't understand what you are stating (I read it "If the user can only set the language through the language selection, the language selection should not be there"), I disagree. The order locale field is intended to represent the locale the user performed their order in. It's important for us to know it (for email sending, PDF generation, …), but it is not important enough to be prioritized over cookie language or browser language (for web pages) nor critical enough that the user can change it permanently (it's very unlikely that the user doesn't understand the language any more in which they performed the full checkout process).

> Also, the missing PDF cache invalidate on order locale change is what it is: a bug
Why not mark this issue as a bug?

You are right, sorry. Of the five problems identified in this issue this is the one that I consider to be a bug that we should fix. I now created a new ticket (#1178) to keep the overview cleaner. I consider it a very non-critical bug, though, since as I said, it's unlikely that a user suddenly stops understanding a language.

> I am aware that we are not paying customers (that is not my choice), but I proposed the use of Pretix to our organisation because I think it is a great system. And because we are not paying customers, I consider it my absolute duty to inform you about all the issues I encounter and all the enhancements that could be useful to us and to others. So you can make an already great system even better.
> Now I have the impression that my feedback is not taken seriously and that you avoid marking bugs as bugs for not showing too much red on the front page? Or closing issues when they are still there for the same reason?

**Wow.** I'm actually not sure how to respond to this in a polite way. In the last week, you opened 13 issues of which I closed five. Of them, one was a configuration error, one was a feature we dismissed years ago after long discussions and where I provided elaborate feedback on why we decided that way, two because I fixed them right away and this one, where parts were a duplicate (which I fixed right away, just to mention it here) and parts were something I don't consider worth fixing because it creates to many other problems.

All other 8 are still open since they are valid change requests, even if we disagree on their priority.
Of course, you not being a paying customer does make a difference in our prioritization, because that's how we make a living in the end.

Take #1174, for example. Of course I agree that it would be great to have that webhook! But as I explained, adding it requires a check of the project to make sure we don't miss a place to make sure it is fired, so building this takes at least 2-3 hours, even if it's a one-line fix at the end. So while I'd merge any pull request for this issue right away after some testing, the only honest answer to "Is this an objective for the near future?" is no, because we're busy and none of our customers cared about it so far and I can't just take 2-3 hours of my day, just because your event is large and you want to start selling so soon. The same is valid for adding the signal (#1171) or all the waiting list issues – I fully agree with the objective, I partly agree with the proposed implementation path, but I just don't have the time to do it *now*. pretix is used by thousands of events on hundreds of servers, and they've all got different needs and our roadmap of features is pages long. 

I'm happy that you provide us with feedback and I'm not sure how any of this is related to not taking you seriously.

**Comment by Zambiorix** [comment]
Clearly I have upset you. That was not my intention and for that I apologise.
There is some misunderstanding.
Because we are non-paying customers, I am fully aware that we have no impact on priority whatsoever and neither do we deserve that. **That is perfectly ok!** I did not mention our event being large to have leverage or to force some priority, I just mention it because the locale issue (I will let it rest) caused confusion and we will get feedback about it. It is just information I pass on to you, that is all.

I have never asked you to solve issue's _now_, maybe I gave you that impression, but that is not correct. I never asked when a bug would be solved or to prioritise anything. Currently, I have a 2.4 version running in Development, Staging and Production and I have workarounds in place for all our needs that are not directly met by Pretix, so we can start selling right now if we want (we don't until March 23).

> Now I have the impression that my feedback is not taken seriously and that you avoid marking bugs as bugs for not showing too much red on the front page? Or closing issues when they are still there for the same reason?

That was out of place. It was mostly related to the bug you missed above and created an issue for afterwards. It was also -and I hope I do not upset you- related to my impression that some of my previous comments or enhancements were dismissed rather quickly or easily. I clearly misinterpreted that, my reaction was uncalled for and I should have been more thoughtful.

Let me apologise again and assure you that we are very grateful for all the hard work you have done at Pretix and your decision to open-source it. I will continue to report about issues we have and about enhancements I see and spam our committee to take a maintenance contract...

**Comment by raphaelm** [comment]
No worries, no harm done! :)

> I would send a case of Belgian beer to make up for the damage, but you have excellent beer in Germany as well and I am not sure sending beer to hard working developers is such a good idea ...

He, no need to do that, but if you insist, let me suggest that Belgian chocolate might be better to ship and more work-compatible :P Our office address is here: https://pretix.eu/about/en/imprint

**Comment by Zambiorix** [comment]
Keep an eye on the mailman on Friday ...

**Comment by Zambiorix** [comment]
Package shows as delivered ..

Enjoy!

**Comment by raphaelm** [comment]
Yes, I received it on my desk minutes ago. Those are *delicious*! Thank you so much! <3

**Comment by Zambiorix** [comment]
I wasn't sure how many employees you have at Pretix, so I sent a bunch
Beware of the sugarshock ;-)
