### ISSUE TITLE
BUG: Stripe confirms payment, yet fails in Pretix

### ISSUE THREAD

**Issue by Zambiorix** [pretix/pretix#1233]
Stripe reports a payment authorised, but in pretix the first event in the order history says that payment failed. Mere seconds later the payment is confirmed.

Unfortunately, the customer sees the failure on his/her screen..
In our case (event sold out in 2 hours) many people who got into this situation thought the whole registration procedure failed and bought a second ticket (and a 3rd, 4th ...)

In the second image you can see what the user sees in such condition. Instead of going to the order link, and error message pops up on the screen and the the home page of the event is shown.. So I understand the confusion of the customer.

![Screen Shot 2019-03-26 at 16 27 56](https://user-images.githubusercontent.com/485492/55010340-5349e400-4fe4-11e9-9ac7-42561e92c35c.png)

![foutmelding](https://user-images.githubusercontent.com/485492/55010636-d53a0d00-4fe4-11e9-9436-d95ae1caee10.jpg)

**Comment by Zambiorix** [comment]
Of course it didn't help that Postmark decided to cap our transactional e-mail service and queued all our outgoing e-mail for the next 4 hours without sending them out.. So people never got that mail until hours later.

Still there is something strange going on in Pretix in this case

**Comment by raphaelm** [comment]
With current pretix and in a "superuser session" (admin mode), you should be able to "inspect" the details of the failed payment and see what exactly stripe sent there and we interpreted wrong. Could you send that data to support@pretix.eu referencing this issue?

**Comment by raphaelm** [comment]
Okay, we received some logs on this from a user, and this seems to be a race condition:

* The user completes the giropay payment
* Stripe sends us a webhook "payment source chargeable", we send a "charge, please" to Stripe.
* While the previous process is *still running*, the user is redirected back to pretix, we see that the source hasn't been charged yet and send a "charge, please" to Stripe. This fails, because Stripe knows they shouldn't process it (because they already received the one triggered by the webhook), but also Stripe doesn't know a proper response yet (because the other request is still being processed).

I'm unsure how we should fix this. Artificially delaying the webhook isn't nice. We could detect the race condition and show users a "please wait a moment" page, which also isn't really nice?

**Comment by Zambiorix** [comment]
Sorry for the late reply, have been offline for a while

I have no clue how you should solve this in Pretix ...

If I have a temporary condition (that must be waited for) in my own applications I usually set up a "processing" page with a websocket to update that page real time when the condition is met (or timed out). But I usually develop SPA's in Vue, not sure how to do that in Django ..  you are the expert :-)


Oh, another topic: I convinced our board to (finally) get a Pretix support contract, but not sure when they'll subscribe. With covid-19, our event has been cancelled this year.

**Comment by raphaelm** [comment]
I think we finally fixed these issues with the fixes for #2165
