### ISSUE TITLE
Cannot set attendee name after checkin

### ISSUE THREAD

**Issue by DerDakon** [pretix/pretix#1254]
After accepting tickets I noticed that no attendee names were provided. I'm not able to set them anymore: when I go to "change details" in the invoice view no edit fields for these tickets show up. I'm still able to change the attendee names if one was initially provided.

**Comment by raphaelm** [comment]
Sorry, I can't reproduce this. Can you e.g. construct a screenshot with multiple tickets in an order where one of the tickets has an edit field and another has not?

**Comment by DerDakon** [comment]
No, I don't have such an entry. And while debugging I found the problem: the checkbox "may entry with this product" was not checked for one single product. I wonder why ticket codes were generated and checkin worked, but after I checked this I can change the settings also in the backend.

**Comment by raphaelm** [comment]
Then this is some kind of misundestanding probably, yes, and I agree, those things are not obvious and we should clear them up at some point. Attendee names are only asked if (a) the product is an admission product and (b) attendee names are enabled in event settings. However, check-in and ticket generation do not need to follow this product selection, you can easily configure them otherwise.
