### ISSUE TITLE
More dependency options for questions

### ISSUE THREAD

**Issue by niklasberlin** [pretix/pretix#1338]
It would be nice to have more options in the dependencies for questions.

right now we have a question for the birthday (type: date) and it would be great to have additional questions when the birthday is before/after a certin date, but i cannot select the Birthday-Question as a dependency for the other questions

**Comment by raphaelm** [comment]
Thanks for the idea! I see why it is useful, especially for a birthdate question. Can you think of other use cases where it is useful?

It feels like it would add a tremendous amount of complexity to both the configuration and the shop interface, so I don't think it's something that we should add lightly. Or, to put it otherwise, if there's just that one real use case, maybe there is an easier way to solve that usecase.

In any case, this should probably be thought in combination with #1168 which also requires to let organizers define restrictions on question answers.
