### ISSUE TITLE
Question: Updating event settings via api

### ISSUE THREAD

**Issue by rimi-itk** [pretix/pretix#1378]
The api does not yet support updating event settings – and for good reasons, cf. https://github.com/pretix/pretix/issues/654. 

Will it be feasible to add an api endpoint for updating (only) General settings for events? Specifically we would like to be able to update `waiting_list_enabled` and `max_items_per_order` both of which are simple settings (checkbox and number).

Best regards,
Mikkel

**Comment by raphaelm** [comment]
Hi Mikkel,

in theory, yes, of course. However, it would kinda be opening the floodgates and all the trouble that comes with a settings API would come very soon and in an unplanned way. Since I couldn't find the detailed reasoning in #654, here's the problem again:

Even if we restrict ourselves to a whitelist of settings to prevent trouble with settings considered internal (and thereby also ignoring the whole plugin ecosystem), we run into a a problem of duplicate code and logic that will really hurt us over time.

Both the *documentation* and *validation* of the settings are only contained in the form layer (all of the SettingsForm subclasses). Adding settings to the API would at the very least require us to copy the description of the settings properties to the API documentation, and even though admittedly the two settings you cited do not require fancy validation, ``max_items_per_order`` isn't just an integer, it's an integer ``>= 1``. If we'd want to enforce that in the API as well, we'd need to copy it as well, creating a large source of bugs in the future.

So, sorry, the only way this is happening in pretix core, is by finding a clean design that allows us to define all of this information in one place and then generate form fields, validators, API serializers and API documentation from there.

Best
Raphael

**Comment by rimi-itk** [comment]
Thanks for your reply. I understand that we're opening up a really big issue here and have to do it the right way – and in a general way to handle all settings and validation etc.

Thanks again.

Best regards,
Mikkel
