### ISSUE TITLE
Widget and web-shop showing different submit button texts

### ISSUE THREAD

**Issue by TimmThaler** [pretix/pretix#1414]
Hi again,

when using the pretix widget on a website the submit button does not say "add to basket" (or something similar) but "enroll / register / subscribe" (german: "anmelden"). I think this is confusing when you sell tickets and customers would like to buy them, but they don't actually see a button for that.

In the web-shop the button says "add to basket".

**Widget:**
![photo_2019-09-19_20-13-41](https://user-images.githubusercontent.com/22148307/65270054-ad061380-db1a-11e9-9961-eea3bbe2a990.jpg)

**Web-shop:**
![photo_2019-09-19_20-13-38](https://user-images.githubusercontent.com/22148307/65270053-ad061380-db1a-11e9-9474-6467263a1a4f.jpg)

**Comment by raphaelm** [comment]
I'd say this is on purpose.

* When using the web shop, you actually get the experience of a shopping card. "Add to cart" / "Zum Warenkorb hinzufügen" makes sense, because the next thing you see is a shopping cart.
* When using the widget, there is no (visible by default) shopping cart. You select your products and go.
* That's why, usually, the button in the widget says "Buy" / "Kaufen". Another reason is that "Zum Warenkorb hinzufügen" is just way to long for many places the widget is used.
* However, "Buy" confused people when there are only free products. That's why we changed it to "Register" / "Anmelden" when all products in the widget are free.

**Comment by TimmThaler** [comment]
Hm, yes, I get what you mean.

But what is with ticket shops that offer free tickets to order (= "buy" in some way), but don't offer tickets like a convention would do, where you "register" with your name etc.? Of course you don't really 'buy' a ticket when it's free of charge, but nevertheless you still order it.
Wouldn't it be more indicated to label the button with something like "order now" or something like that?
This way you won't have a confusion when labelling the button with something with "add to cart" or "buy", but still have a hint that you are going to order something like a ticket or sth. else.

**Comment by raphaelm** [comment]
The thing is that "Order", just like "Buy" is connected to paying in peoples minds. When expecting a free thing, "Order" or "Buy" makes you hesitant to proceed since it sounds like it will cost money at some point.

Can you tell me more about use cases where "Register" is not applicable? I don't think it's a good choice only for conventions but also for free workshops and maybe even free parties. The same goes for the German translation of "Anmelden".

**Comment by TimmThaler** [comment]
I share your concerns that people could think "ordering" and "buying" are the same things, specially because meanwhile online shops have to show a button like "kostenpflichtig bestellen" at checkout.

In my special case, a theatre group offers to get their tickets online. The tickets are free of charge, so the guests don't buy the tickets, but they still order them and receive them via e-mail. 
The guests don't register in the common meaning as the theatre group is not interested in names etc. of the people. I haven't recognized a "big" theatre, yet, that let's its guests register for a show - the people buy / order tickets.

I didn't want to make a big thing out of this "issue". It just cought my eye that there are different button labels at shop and widget.

Probably my language understanding is just a bit too fussy. 😄
