### ISSUE TITLE
Dashboard not showing Attendees (ordered) or (paid)

### ISSUE THREAD

**Issue by buttle** [pretix/pretix#1419]
Hi,

Since the last update, the dashboard of an event shows "0 Attendees (ordered)" and "0 Attendees (paid)", when in fact **there are attendees** who have paid.

Clicking on both 'ordered' and 'paid' does correctly show the orders.
Any thoughts?

Cheers.

**Comment by raphaelm** [comment]
I'm pretty sure that this is not at all related to the last update but your products are just missing the checkbox "Is an admission tickets". Only these products are counted on the dashboard. This is intentional: if you sell e.g. t-shirts and tickets you would only want tickets to be counted towards your attendee number.

Feel free to reopen if this is not the issue.

**Comment by buttle** [comment]
That was it! Thank you.
