### ISSUE TITLE
Shared reports: no progress bar if quota is overbooked.

### ISSUE THREAD

**Issue by TimmThaler** [pretix/pretix#1449]
Hi there,

I just recognised that in shared reports the progress bar disappears if its quota is overbooked. After having a look at the html code I would guess, that there is no css class for i. e. `progress-bar-104`. Perhaps one could add a css class "overbooked" for values >100%.

As reserved tickets are represented in orange, it would be nice to have a red coloured progress bar for those overbooked quotas.

![Bildschirmfoto 2019-10-16 um 11 36 39](https://user-images.githubusercontent.com/22148307/66908119-d4150f80-f00a-11e9-9c84-c1554e221162.jpg)

**Comment by pc-coholic** [comment]
93c68a605f80462b5390cf539f4b2ac15e972c9b

**Comment by pc-coholic** [comment]
Thank you for pointing this out!

Unfortunately, we cannot extend the progressbars futher than 100% - so we have to work around this a little bit...

Instead of coloring the progressbar red (as it is a little difficult to decide, what is being colored red: the sold tickets? The reserved tickets? Both? Parts of both?), we opted to display the progressbar in a striped pattern.

You should find the changed version deployed on pretix.eu within the next 10 minutes.

**Comment by TimmThaler** [comment]
Thank you!
It really looks good!

**Comment by TimmThaler** [comment]
With coloured red I meant that perhaps the whole progress bar could be red to show that the quota is overbooked.
But the stripes look nice, too :)
