### ISSUE TITLE
Suggestion: Support DataMatrix

### ISSUE THREAD

**Issue by larsfu** [pretix/pretix#1470]
As DataMatrix supports non-square symbols (even without the not so widely supported DMRE extension), it seems especially suited for tickets in the usual aspect ratio. It saves spaces and is (imho) more aesthetically pleasing than QR:
<img src="https://i.imgur.com/9j97zws.png" />
If this is something you endorse and consider feasible, I would like to look into it.

**Comment by raphaelm** [comment]
Hmm, yes indeed, that looks nice! I'm a bit concerned about scanning speed. First of all, QR codes are really well-supported when scanning with smartphone cameras because they are easy to detect from every angle, which I'm not sure is as true for DataMatrix. Second, being non-square might look nice, but also means that the distance between the two outmost parts of the code is larger, thus reducing the range of distances it can be scanned from with a hardware-based scanner. Does anyone have experience with this?

If we want to adopt this (optionally, of course), we'd need to deal with quote some tasks, so it will be some work involved:

* Add an option to the ticket layout editor to not only switch between QR and DM, but also resize DM codes to a non-square format (while still only allowing squares for QR codes)

* Add DataMatrix rendering to both our Python-based PDF renderer as well as both versions of libpretixprint, our Android-based PDF renderer

* Make sure both pretixSCAN Android and pretixSCAN iOS can scan it, both with the system camera as well as with supported hardware scanners
