### ISSUE TITLE
Assign team limitation to event during creation.

### ISSUE THREAD

**Issue by MaicoTimmerman** [pretix/pretix#1485]
With the introduction of pluggable authentication (#775) we are now able to provision our users automatically with teams upon login. We allow any of these users to create new events, however we would like the new events to be limited to these teams only. I could not find any open or closed issues except for #914, which is a somewhat similar issue.

Currently when a user has no team allowed access for all events under an organizer, a new team is provisioned:
```python
 t = Team.objects.create(
                    organizer=event.organizer, name=_('Team {event}').format(event=event.name),
                    can_change_event_settings=True, can_change_items=True,
                    can_view_orders=True, can_change_orders=True, can_view_vouchers=True,
                    can_change_vouchers=True
                )
                t.members.add(self.request.user)
                t.limit_events.add(event)
```

We would like the user to be able to select a team during event creation.

My suggestion would be to add a step during event creation, which checks whether the user is in a team with control rights, similar to the current check in the Event wizard:

```
            has_control_rights = self.request.user.teams.filter(
                organizer=event.organizer, all_events=True, can_change_event_settings=True, can_change_items=True,
                can_change_orders=True, can_change_vouchers=True
            ).exists()
```

If such a team is not present, show an additional final event creation step in which the user can select a team or would like a team to be provisioned.

I'd be happy to make an attempt at such a pull request.

**Comment by raphaelm** [comment]
Hmm, I see the problem here, and I also am sometimes annoyed by the many auto-generated teams, so I think it makes sense to let users optionally select an existing team during event creation instead of a new one being created. It doesn't really fit the data model of teams (in theory, you'd need to select N teams that should gain access to the event), but it's a start.

However, I'm cautious of making the event creation process more complex, as this is the very first thing people see of pretix and it should therefore be clear and fricitonless. Most people do not know what teams are at that point.

Therefore, I'd suggest:

* Not adding an additional step, but instead just a form field to the second step
* Only showing the field in the case where we would currently create a new team, as suggested

Feel free to create a PR! :)

**Comment by MaicoTimmerman** [comment]
@raphaelm I have created a pull request, please let me know what you think.
