### ISSUE TITLE
Can't get PayPal to work

### ISSUE THREAD

**Issue by ajpierson** [pretix/pretix#1528]
I can't figure out how to get PayPal enabled.  I have a self-hosted system set up.  I have generated the API keys and configured the webhook on PayPal, and added the keys to the general settings for my site.  I added the PayPal plugin, but I'm not able to enable it for my event, all it has is the "Connect with PayPal" button, which I understand to be the way it's configured if it's the hosted version, but I tried clicking it anyway and it says "Looks like this action is not supported" and the reason is "Invalid Scope" What am I missing?

**Comment by pc-coholic** [comment]
You probably have the wrong API-keys for what you're trying to do: Your API-keys are already bound to a single PayPal-Account.

Just remove them from your global settings and go to your PayPal-settings on the event.

There should now be an input field for your PayPal-keys instead of the Connect-Button.

Same thing for Stripe, too, btw ;-)

**Comment by ajpierson** [comment]
Wow, that was it, thank you so much!
