### ISSUE TITLE
Ask for country-specific tax numbers in invoice addresses

### ISSUE THREAD

**Issue by patrick91** [pretix/pretix#1533]
Hi there, I wasn't able to find this in the docs, but I was wondering if it is possible to always ask for VAT, even in the individual invoice information:

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/667029/71213566-23e6b000-22b4-11ea-8ea6-3d6e21103f05.png">

The reason we need this is that in Italy we need to send e-invoices to our customers, and in order to do that we need their "fiscal code" (which is similar to a VAT in a way). Is there an option to enable this? :)

**Comment by raphaelm** [comment]
I would strongly recommend "abusing" the VAT ID field for this, since the VAT ID field will validate the input against the EU VAT ID database and will reject anything else.

We have a similar request from a client on our roadmap (for Australian Business Numbers), and we're considering introducing a way to re-label the "Internal reference" field with a custom label or adding another field that can be freely labeled.

We currently scheduled this feature for "somewhere in the first quarter of 2020", but if you need it more urgently I can have a look at what we can do in january (or accept a PR; of course).

**Comment by patrick91** [comment]
@raphaelm, for now, we added a custom question, not ideal but might work :)

I think adding a new field would be ideal, not sure if the internal reference would be fit for that. I'm going to think about this a bit more and let you know if I still think it is better to add a new field :)

**Comment by raphaelm** [comment]
Fixed by now!
