### ISSUE TITLE
Where are the Reports?

### ISSUE THREAD

**Issue by ajpierson** [pretix/pretix#1543]
I have the Report Exporter plugin installed, but I don't see anywhere to get any reports.  Do I need to configure something else?

**Comment by pc-coholic** [comment]
Since this is an Enterprise Plugin, please feel free to contact support@pretix.eu directly :-)

To answer your question: The reports plugin adds a new navigation item on the top level navigation - it is visible directly after logging into the backend at `https://yourhost.com/control`. The menu item will however not be visible once you start selecting an Organizer or Event.

**Comment by pc-coholic** [comment]
Oh, sorry - I might have misunderstood you there...

The "Reports Plugin" that you probably mean is not an Enterprise plugin - sorry for the confusion...

You will find those exports within your Event -> Orders -> Exports.

**Comment by ajpierson** [comment]
Yes, that is exactly what I was looking for, thank you!
