### ISSUE TITLE
Relative availablities for products

### ISSUE THREAD

**Issue by pc-coholic** [pretix/pretix#1567]
When setting up product availabilities right now, we only accept absolute dates.

However, in the context of eventseries that might want to sell early bird tickets, this is not very useful, if there is early bird tickets for every single date/performance.

We could counter this by extending the absolute dates with our relative date/time-picker and tie the relative dates to the subevent's date.

Z#2355699

**Comment by felixrindt** [comment]
I've been looking into this and hit a point where I wanted to ask you about how to progress.
I tried to use the `reldate.ModelRelativeDateTimeField` on an `Item` and then look into how filtering works. In

https://github.com/pretix/pretix/blob/76aaf61e1905acd1e868e66539c61d1b390db554/src/pretix/base/models/items.py#L168

we do the date-based availability check using a queryset, but that wouldn't be possible when the availability fields are relative and need to be checked on instances. 

My strategy now would be to actually do that and move the check to relevant places in code (making it slower). We'd need to juggle around references to a possibly existing subevent (otherwise as an item use dates relative to `self.event`) to determine availability. 

Do you have any thoughts on this?

**Comment by raphaelm** [comment]
That might actually be a show-stopper for this feature, at least for now. The filter for available items is used in lots of very performance-critical paths, such as the event front page or the list of events where we need to determine whether a product is available for lots of events.

Maybe we need find a new representation of relative date times in the database to do this :(
