### ISSUE TITLE
Voucher for multiple products

### ISSUE THREAD

**Issue by patrick91** [pretix/pretix#1573]
Hi there, we were trying to create vouchers that would work on multiple products, but noticed that we can only select one product or a quota. 

Is there a way to select multiple products for the same voucher?

We want to give vouchers that work for multiple tickets as we have some tickets that will expire after a set date, but we also don't want these voucher to work on all the tickets :)

Does that make sense?

**Comment by felixrindt** [comment]
I think you should be able to create an unlimited quota and include the voucherable tickets you want in that quota, then make the voucher apply to that quota.

**Comment by raphaelm** [comment]
What @felixrindt says :)

**Comment by choseh** [comment]
That won't allow reservation of spots in the invidual products' contingents though, which would be nice. Currently facing the same issue where there are 4 Tickets (with 4x waiting list, because reasons...) and I cannot find a way to create a voucher that reserves spots in all of them.

**Comment by raphaelm** [comment]
Yeah that won't happen :(

**Comment by choseh** [comment]
@raphaelm maybe waiting lists for add-on products happen some day, then I won't need this ;)

**Comment by idna001** [comment]
I'm facing the very same problem from @patrick91 from 2020, but for a different reason:
I do have multiple products with very different quotas.

Currently, vouchers can only be assigned to individual products or quotas. 
Managing vouchers across multiple products becomes cumbersome, especially when aiming to restrict their applicability to certain items without creating numerous individual vouchers. 
It would be highly beneficial to have the functionality to apply vouchers to multiple selected products or entire categories, enhancing flexibility and efficiency in voucher management.

In my current system, I have to send out multiple coupons to one costumer, because I often don't know in which product he is interested in. 

This is sadly a required feature for my event..
Are there any plans for such an improvement, or other ideas how can I solve my problem?
Greetings
Andi

**Comment by ajasja** [comment]
Same problem here -- I have three products that I want reduced, but not more.

**Comment by raphaelm** [comment]
What's preventing you from creating an (unlimited) quota that groups them?

**Comment by idna001** [comment]
@raphaelm I just wanted to clarify that in my case using an unlimited quota is not an option –  
I explicitly need the quotas to stay limited, since I don’t want to risk overbooking the available spots.  
That’s why grouping them into an unlimited quota unfortunately doesn’t solve the problem for me.

**Comment by raphaelm** [comment]
> @raphaelm I just wanted to clarify that in my case using an unlimited quota is not an option –  
> I explicitly need the quotas to stay limited, since I don’t want to risk overbooking the available spots.  
> That’s why grouping them into an unlimited quota unfortunately doesn’t solve the problem for me.

If you create an additional unlimited quota, that still works. A product is only available if all quotas it is contained in are available, so there shouldn't be a problem.
