### ISSUE TITLE
Question: Testing the digital content plugin

### ISSUE THREAD

**Issue by rimi-itk** [pretix/pretix#1623]
Thanks for the quick reply and action on https://github.com/pretix/pretix/issues/1618.

I've enabled the digital content plugin on a test shop hosted on pretix.eu and created some digital content. After placing a paid order (using the fake payment providers plugin) I cannot see the digital content on the order confirmation page.

1. Do we have to pay for the plugin for it to show content on the order confirmation page (https://marketplace.pretix.eu/products/digital/pricing)?
2. Do I have to use a real payment provider to see the digital content after completing a purchase?
3. Any chance that digital content will also be available for free tickets (our most common use case) (cf. https://github.com/pretix/pretix/issues/1618#issuecomment-603313897)? We will gladly pay for the plugin, but are there any specific reasons for not enabling digital content for free tickets? 

Best regards,
Mikkel

**Comment by raphaelm** [comment]
Since this is not a pretix core issue, can we move this to email (support@pretix.eu) and can you also tell me which event on pretix.eu this is? Then I can look why the content does not show up (it should, in the situation you describe).

To give quick answers here:

1. On pretix.eu, no, you do not need to pay extra. If you self-host pretix, yes you do.
2. No, fake payment provider should be fine.
3. Ah, by paid tickets I meant "order status = paid" which always should be the case for free tickets.
