### ISSUE TITLE
Feature Request: Timezone display offset

### ISSUE THREAD

**Issue by ligi** [pretix/pretix#1644]
it would be great if the timezone offset to UTC would be displayed in the dropdown menu.

**Comment by raphaelm** [comment]
Sounds really helpful and simple on first thought. On second thought, I'm not so sure any more:

The UTC offset is not a static property of a timezone, it depends on the date, e.g. if daylight time changes or time zones are redefined. 

Contrary to most computer systems, pretix deals a lot with datetimes in the future, e.g. when you select a timezone, you're currently setting up an event and have just specified the date and time of your event. You might be setting up an event in summer, but it is still winter. If the select would show the UTC offset, a naive user might select a timezone with the correct offset for their event, not for the current time, which will lead to the wrong timezone. We've also seen cases of rapidly changing timezones (i.e. countries moving the date of daylight saving time by a few weeks on short notice).

Additionally, in many places you will see multiple dates on one page (e.g. the date of an order and the date of the event the order is for) which have the same timezone, but different offsets.

I therefore think it might actually be less confusing to force users into thinking of timezones as "location"/"legislation" instead of "offsets".

Any thoughts?
