### ISSUE TITLE
Voucher does not get reactivated on canceled orders

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#165]
If you use a voucher for an order, and the order gets canceled, the voucher is still marked as used. That is incorrect behaviour, in my opinion.

**Comment by rixx** [comment]
Ah, apparently introduced in ce6e8d0f.

**Comment by rixx** [comment]
I think a reasonable default would be to create the voucher(s) if any variation is still available and the sum of available items is larger than the amount of vouchers generated.

**Comment by raphaelm** [comment]
When I implemented vouchers, I accepted this because I feared for surprising scenarious if redeemed vouchers do get reactivated. Hence the decision for a ``redeemed`` field instead of checking ``is_ordered`` all the time.

After thinking for a while, I believe I found such a scenario: 
Currently, it is possible to cancel an expiring order. Quota Q with item P is of size 1. The admin creates voucher V with ``valid_until=None`` and ``block_quota=True``. Now the quota pool is empty. An order is placed using that voucher, the quota pool is still empty. The user does not pay and the order expires, hence again quota is available. Another user orders a ticket, quota pool now is empty again. The first order gets cancelled and the voucher gets reeneabled. This voucher can now be used and the event will  be overbooked.

A solution could be to disallow cancelling expired orders which would require some thinking about other scenarios with similar problems.

**Comment by rixx** [comment]
Picking this up again in #201 - so if we'd disallow cancelling of expired orders (which makes a lot of sense to me), you'd be willing to go ahead with this? I added it to the new PR as a separate commit, so it can still be taken out.

Funnily enough, the "Cancel order" button was already only shown if the order was still marked as pending in the frontend. (Cancelling was allowed in the view, but the button was … just not there :D).

Maybe a shortcut like `can_user_cancel` for `is_cancellable` (basically `self.status == self.STATUS_PENDING`) would be nice, unless you'd like to introduce a state machine … ;)
