### ISSUE TITLE
The order of products is not stable between event page, cart, checkout

### ISSUE THREAD

**Issue by thegcat** [pretix/pretix#1663]
The event page will show products in the order defined for products in the event settings, the cart at the top of the event page and the checkout pages will not always show the same order. This was confusing to me when I first noticed it :-)

As best I can surmise the products in the cart are sorted in the order the products were created (I can't say if this is by ID or by whatever order the DB happens to return). The products seem to be in the same order they have been added to the cart on the checkout pages (same as before, can't say if it's intentionally sorted by ID or whatever order the DB returns). It is very confusing that products are sorted differently in different parts of the app.

**Comment by raphaelm** [comment]
There's two aspects to consider here that pretix handles differently:

* Cart items that contain any specific sub-items (such as download buttons, answers, add-on products) are currently shown in the order of their cart position ID. I think we should keep it this way (so if I add something to my cart later, it appears at the bottom), but should double-check that products are added to the cart in the order the products show up on the event page if I add multiple products at once.

* Cart items that are not specific and can be grouped (e.g. shown as "2x Regular ticket" instead of 2 lines with "Regular ticket") are apparently currently sorted by their product ID, which does not make sense, and should be based on the product and category order instead, agreed. This is handled in the inline ``keyfunc`` function in ``pretix/presale/views/__init__.py::CartMixin::get_cart`` which is used both for grouping and for sorting (which makes it a bit nasty to work with)

**Comment by raphaelm** [comment]
Fixed by #1473
