### ISSUE TITLE
Corona: Distance Seats per order (easy algorithm)

### ISSUE THREAD

**Issue by stebla27** [pretix/pretix#1790]
In times of Corona it's very difficult to define a maximum seating capacity for an event because the number of seats strongly depends on the size of groups (e.g. familiy size).
Example:
An event place has 10 seatings. There must be a distance between households of 3 places.
Option 1:
Only single persons order a ticket. ==> Only 3 person can se seated safely (1 + 3 + 1 + 3 + 1 + 3)
Option 2:
Only families with 2 person per order. ==> 2 + 3 + 2 + 3 = 4 person can be seated safely
Option 3:
One big family with 5 person and one with 2 person ==> 5 +3 + 2 ==> 7 person can be seated safely

As you can see it's very difficult to define  maximum seating places for an event with no seating plan.

Idea:
Each event defines a customer specific distance (e.g. 3 seatings). This distance is automatically subtracted from the free seating places with each order. This is also no 100% good algorithm but however it simplifies the situation a lot.

**Comment by raphaelm** [comment]
I understand the issue, but I personally don't think this makes too much sense without a seating plan, since it completely ignores that space is not one-dimensional.

For example, given that you have a venue with two rows of 10 seats that have enough distance between them, you could easily fit the following groups:

```
X...XX...X
XXX...XXXX
``` 

Whereas in a venue with one row of 20 seats, you couldn't fit the same groups. I really don't think it makes sense to think about event venues in one dimension.

Additionally, it would be quite hard to implement without lots and lots of additional complexity as well as a large performance impact because it doesn't really fit the way pretix thinks about quotas.
