### ISSUE TITLE
Skip Order Stage

### ISSUE THREAD

**Issue by Frammo** [pretix/pretix#1794]
Would br great to have an option to skip the ordered email to customers. When used with Stripe they pay straight away and then get 2 emails (Ordered, Paid) at the same time which can be confusing. 

Obviously I see the need for the extra step using when using other payment methods. Might be an idea to have customer notification options per event.

**Comment by raphaelm** [comment]
No, we can't skip that mail. It's the only safe way to recover if the stripe payment fails. We'd love to consolidate both into one email, but we think the required complexity (send first email only if payment not occured within X minutes, otherwise send combined email with different text) isn't worth it.

**Comment by raphaelm** [comment]
See also #1167
