### ISSUE TITLE
Sometimes stuck on trying to reserve

### ISSUE THREAD

**Issue by aerugo** [pretix/pretix#1802]
We have started running into a strange problem since we updated to 3.11.0. Every once in a while, something goes wrong and the server stops being able to reserve tickets and add them to the cart. It just leaves you hanging on the "We're now trying to reserve this for you!" prompt. 

When this happens, it happens for all organizers and events on the instance. This can be solved by restarting Pretix, but the problem usually comes back within a couple of days.

I have checked the logs in /var/pretix-data/logs, but nothing shows up. 

This problem is a little hard to reproduce consistently, so testing has been difficult. If it helps, I could look into other logs to help debug.

**Comment by ben-hearn-sb** [comment]
For images sake it is this dialog

![image](https://user-images.githubusercontent.com/13691166/95719546-43e6c600-0c70-11eb-98c3-0d601431bc1f.png)

**Comment by raphaelm** [comment]
How do you run pretix, with or without docker?

**Comment by raphaelm** [comment]
The OP has since purchased a pretix Enterprise support contract and together, we got to the bottom of this:

One organizer in the system had a web hook configured that regularly took 60s to time out, which caused congestion in the task queue.

Ideas for the future:
* Make it easier to run the docker image with more celery threads
* Make it easier to run the docker image with separate celery queues
* Auto-disable webhooks if they fail to often (like we already do in pretix Hosted)
