### ISSUE TITLE
Email preview broken after reload

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#1879]
Just a small frontend bug, which I found as follows:

1. Go to an event's email settings
2. Edit one of them
3. Check the preview to see how it looks
4. Satisfied and happy, click "save" (Page gets loaded again)
5. Click back to the email text you edited: It's still open on the preview tab, and the preview tab is completely empty

Nothing big, but I first thought that pretix had somehow discarded the whole email text, so maybe worth fixing.

*Browser:* Firefox 85 (current).

**Comment by wiffbi** [comment]
Interesting, Firefox keeps the location.hash when POSTing to the URL and getting redirected to the form’s original URL. Because of this, the preview-tab is open (even getting the .active-Classname), but its containing parent datails.panel is closed (should be open). And preview is not rendered, because preview render is bound onclick of preview-data-toggle. If class .active is applied, trigger a click-event on preview toggle?

**Comment by raphaelm** [comment]
Generally, keeping the location hash is a nice feature, especially when it's used for our "main tabs", e.g. when switching between SMTP settings and text settings it makes sense to show the same tab again that was edited by the user.

It does not make any sense for nested tabs, or even "tabs > collapsible > tabs" like we have here. Can we maybe just prevent the location hash to be used for *nested* tabs?

**Comment by wiffbi** [comment]
Should be possible, I will look into it.
