### ISSUE TITLE
booking statements aren‘t recognized in csv upload

### ISSUE THREAD

**Issue by vflg** [pretix/pretix#1900]
I uploaded a csv file with a few bookings. The system didn‘t automatically recognize the columns so I manually matched them to the provided fields.
After continuing, no booking could be connected / resolved to the orders, saying that no order numbers were found. Then I manually copied the order numbers from the bookings to the order number fields. Every booking contained the correct order number and was found when i pasted it into the field

**Comment by raphaelm** [comment]
Can you maybe share 1-2 anonymized lines of the file?

**Comment by vflg** [comment]
`"Auftragskonto";"Buchungstag";"Valutadatum";"Buchungstext";"Verwendungszweck";"Glaeubiger ID";"Mandatsreferenz";"Kundenreferenz (End-to-End)";"Sammlerreferenz";"Lastschrift Ursprungsbetrag";"Auslagenersatz Ruecklastschrift";"Beguenstigter/Zahlungspflichtiger";"Kontonummer/IBAN";"BIC (SWIFT-Code)";"Betrag";"Waehrung";"Info"
"[IBAN anonymized]";"04.01.21";"04.01.21";"GUTSCHR. UEBERWEISUNG";"[Event name] 2021 [EVENT NAME]-3HHUK ";"";"";"";"";"";"";"[Name anonymized]";"[IBAN anonymized]";"[BIC anonymized]";"10,00";"EUR";"Umsatz gebucht"
`

**Comment by vflg** [comment]
any idea why this is not working with the shared lines of the file?

**Comment by raphaelm** [comment]
So far, now. Assuming that ``[EVENT NAME]`` is the correct short form of the event, this should absolutely work correctly.

(in case you are a customer of pretix hosted or enterprise, feel free to reach out privately at support@pretix.eu with the real data to check further)

**Comment by vflg** [comment]
I looked into an E-Mail with the {payment information} and found out, that because I set the prefix for the "Intended use" to the event name, too. I removed the prefix and will check if future orders will be recognized correctly.
Anyway the "intended use" is generated by pretix itself and inserted in the {payment info} in the order confirmation e-mail so it should be recognized with the prefix, too.

**Comment by raphaelm** [comment]
What do you mean by "intended use"?

Anyhow, feel free to reopen if the issue persists

**Comment by vflg** [comment]
sorry I didn't look up the correct translation.. I meant the "reason for payment" 

I think its an issue no matter if it works with the new setting - if it works, the prefix is not noticed correctly.
I can't influence what's in the {payment info} in the order confirmation, this is totally in pretix hand.

**Comment by raphaelm** [comment]
It's absolutely possible there's a bug here, but with the current information it's likely not yet possible to find and fix it, sorry. We recently changed some things in the detection logic, but thousands of real payments have processed through this parser since, and we're having automated tests in place for both the [CSV parsing](https://github.com/pretix/pretix/blob/master/src/tests/plugins/banktransfer/test_csvparser.py) as well as the [order code detection](https://github.com/pretix/pretix/blob/master/src/tests/plugins/banktransfer/test_import.py).

So I'm confident it is not broken in the general case, and any of the following is likely true:

* You made an error when assigning the columns of the CSV file to their meanings. To try this again, you could import a CSV file of completely different structure (to make pretix forget the current meaning assignment), and then import your file again).
* A bug is triggered by something unusual about your file that is not yet apparent from the excerpt you posted.
* A bug is triggered by something unusual about the short form name of your event (does it include any non-alphanumeric characters?) that we currently don't test for

**Comment by vflg** [comment]
so i tested it again and maybe I received the wrong cdv format in the earlier test. The orders where correctly marked as paid now.
