### ISSUE TITLE
Error cause in email content is hidden

### ISSUE THREAD

**Issue by ligi** [pretix/pretix#1912]
see this screencast:

https://user-images.githubusercontent.com/111600/105035310-11ace780-5a5b-11eb-9eb9-a0385b95f916.mp4

could be solved these ways:
 * expand by default (or keep expanded)
 * indicate the error in the section

**Comment by wiffbi** [comment]
Sorry, can you give more context. The screencast/video seems broken and no video is shown.

**Comment by ligi** [comment]
Can you try another browser?

**Comment by wiffbi** [comment]
Oh, tried Firefox and Safari as well as downloaded the video but no luck. Chrome did the trick. The problem is that pretix currently does not track opening status of these details/summary-fields in the URL (which currently is the only way to track open status of tabs) – that is needed to open the tab after the page-reload when clicking „save“.

As multiple details/summary-fields could be opened at once, the URL is not a great place to put this status-info IMHO (although it would be nice, because you can share a URL with a specific tab opened). So for foldout details/summary-field localStorage might be a way to persist that info – although this might seem strange if you return to the page at a later stage and thanks to localStorage certain details-fields are opened.

A more pragmatic approach – and probably not to hard to implement – would be to open all details-fields that contain form-errors.

**Comment by raphaelm** [comment]
> A more pragmatic approach – and probably not to hard to implement – would be to open all details-fields that contain form-errors.

We already do that with tabs (as can be seen here with the red :warning:) and also with collapsibles in the shop checkout, so we should already have code for that somewhere:tm:

**Comment by wiffbi** [comment]
Yes, I think it is in `pretixpresale/js/ui/main.js#L152-L154` and `pretixcontrol/js/ui/main.js#L603-L605`. I will look into this.

**Comment by raphaelm** [comment]
I came across this again while working on exporters and fixed it in the same go

**Comment by wiffbi** [comment]
Thanks!
