### ISSUE TITLE
Regex to validate answer to text question

### ISSUE THREAD

**Issue by thegcat** [pretix/pretix#2021]
We are collection the Matrix ID of participants in some of our events and consistently have users entering their Matrix ID wrong. It would be helpful to be able to define a regex the answer to a question needs to match.

Is this something that would be interesting to have in Pretix, or should we create a custom plugin with a custom question type?

**Comment by raphaelm** [comment]
I don't think we want this in pretix, but we've already thought about adding a plugin hook that allows this easily.

**Comment by thegcat** [comment]
A Plugin hook would be more than enough, though I'm not sure how it would be configured? Would you need to select the question that should match something in the plugin's settings? It would be great to be able to configure it in the question's settings directly even if it's a validation/regex provided by a plugin.

**Comment by raphaelm** [comment]
You could just base it on a well known question "identifier" like ``matrixid`` that needs to be used for the validation to kick in.

**Comment by thegcat** [comment]
Funnily enough that sounds like "magic" I'd expect in the Ruby/Rails realm but not in Python realm 😬

That would solve our problem but would not be maintainable/discoverable enough for us.

Next idea, would creating a new question type from a plugin be something doable? That would also enable having more generic validation options rather than just regex? That would also allow throwing in some client-side validation in the HTML and other niceties, even if it makes the plugin more complicated.

**Comment by raphaelm** [comment]
Leaving the language snark aside, if you want this as a nice/discoverable feature (which I can fully understand), then I think the answer to the feature request is "no". I believe having user-specified regex validation is too edge-casey and too technical for a first-class feature in pretix. I'll be closing this issue for now, we'll likely add the plugin API in anways.

> Next idea, would creating a new question type from a plugin be something doable? That would also enable having more generic validation options rather than just regex? That would also allow throwing in some client-side validation in the HTML and other niceties, even if it makes the plugin more complicated.

I'd love if we could do that, but I don't think we will or should. Our questions are a feature that extends beyond pretix across the full ecosystem – input and output of questions also happens in our pretixSCAN and pretixPOS apps as well as other API clients. Keeping these in sync with the existing question types and validating rules is already something we do a poor job at, but allowing plugins to add more question types would leave the user entirely confused as to which types work in which part of the ecosystem.

Note that you *can* add additional fields to the questionnaire through the ``pretix.presale.signals.question_form_fields`` signals which are stored in the ``meta_info`` dictionary instead of in a question and the plugin has to deal with validation and display individually.

**Comment by raphaelm** [comment]
FWIW, the plugin API is now implemented in dafee9ad7 and a plugin in https://github.com/pretix-unofficial/pretix-regex-validation

**Comment by thegcat** [comment]
Oh nice, thanks! I'll try to give it a spin, though I might not get to it before the next stable release.

**Comment by MoralCode** [comment]
if regex validation is not desired, would it be better to instead have a dropdown of options for common patterns? I'm looking at the same usecase (validating matrix IDs) and would love to see a dropdown when setting up a question where i can select from a list of a pre-defined validations that can be applied to that field such as: matrix ID, social media handle, email address, url, .etc
