### ISSUE TITLE
plugin api: add a signal for new event created

### ISSUE THREAD

**Issue by MaicoTimmerman** [pretix/pretix#2087]
I'd like to add a new signal, that fires when a new event is created to set some sane default settings for our plugin. 

My suggestion would be to let `pretix.base.models.event.Event.set_defaults` fire a new event named `pretix.base.signals.event_created` to be in line with the `checkin_created` signal.

Before I start working on this, are you open to new plugin signals?

**Comment by raphaelm** [comment]
Generally, yes, I'm open to new signals if they make sense.

However, for the use case you describe, I don't think you need one.

If your plugin's settings live in our settings store, you can add defaults more elegantly like this: https://django-hierarkey.readthedocs.io/en/latest/quickstart.html#set-default-values

If they live e.g. in a model, how about doing it in

* the event copy signal for copied events
* the plugin's installed method to trigger after plugin activation instead of after event creation: https://docs.pretix.eu/en/latest/development/api/plugins.html#signals

You'd only really need an "on event create" for a plugin that's enable by default globally, wouldn't you? Maybe we should just call installed() in that case?

**Comment by MaicoTimmerman** [comment]
That seems to work great, I've created #2089 to make sure that `installed()` is called for all instance that an event is created.
