### ISSUE TITLE
notify_incomplete_payment triggers if customer has multiple order positions

### ISSUE THREAD

**Issue by rp3r** [pretix/pretix#2366]
**Describe the bug**
If using banktransfer the notify_incomplete_payment is triggered multiple times if an customer has multiple order positions.
Customers get the `order_expire_warning` mail for each position that isn't paid.
Example:
- Customer has 4 position, each 7€
- Banktransfer matches an 28€ transaction with that order
- Each position is handled individually so there is still an unpaid `pending_sum` open until the last one
   - position 1 paid with 7€ (21€ still unpaid => `order_expire_warning` mail triggers)
   - position 2 paid with 7€ (14€ still unpaid => `order_expire_warning` mail triggers)
   - position 3 paid with 7€ (7€ still unpaid => `order_expire_warning` mail triggers)
   - position 4 paid with 7€ (nothing unpaid => payment confirmation mail is send)

`mail_days_order_expire_warning`-settings is set to 0.

**Expected behavior**
No expire warning mail should be send unless the banktransfer is completed or at least the `mail_days_order_expire_warning` setting should be taken into account.

**Screenshots**
![image](https://user-images.githubusercontent.com/24244565/144591019-44c3e69d-cb65-4cb9-b3f6-6fb623c801e1.png)
Please ignore that it begins with "Zahlung 2", first payment was canceled.

**Additional context**
We're still on version 3.16, but planing to update our system soon.

**Comment by raphaelm** [comment]
Hmm, this is a tough one. I'm strongly leading towards a "wontfix".

Generally, I do not feel it is an intended use case of pretix that multiple people send the money for the same order independently. We intentionally do not support rate payments or similar things.

What you're running into is a mechanism that tries to solve the following problem: When someone pays too little money, it is usually an accident. For example when transferring money internationally, it is common for a few euros to go missing due to banking fees etc. This might lead to confusion and people losing their tickets because the order is not marked paid. To save the organizer some trouble, the bank transfer plugin contains a small piece of code that sends an email to the customer whenever a partial payment has been made. Since we wanted to avoid introducing additional configuration for this since there's way too many configuration already, we're using the text of the payment reminder, although with a different, more specific subject. So far, this has been a good balance in many cases.

**Comment by rp3r** [comment]
The main problem is that the customer sends just one payment and this is splitted onto different positions and each will trigger an email. It is really confusing for the customers as they get a couple of mails with "incomplete payment" altough they payed enough for the complete order.
For example a customer has 100 order positions in one order and he pays all in one transaction, he'd receive 99 mails with incomplete payment.

The function in general is completly fine and works perfectly around your problem with international banking or banking fees.

**Comment by raphaelm** [comment]
>  For example a customer has 100 order positions in one order and he pays all in one transaction, he'd receive 99 mails with incomplete payment.

I'm 100% positive this is not the case. The email you are referring to is sent *once* and not for every position and it is *only* sent on *incomplete* payments.

The example in your screenshot received 3 emails because they paid in 4 batches, not because they ordered 4 tickets.

There is absolutely no connection between order positions and payments **anywhere** in pretix, the concepts are thoroughly isolated from each other.
