### ISSUE TITLE
Availibility informations (paid order, etc..) not sent on unlimited quota via API

### ISSUE THREAD

**Issue by rapinf** [pretix/pretix#2416]
Hi,

I use availability API to get paid orders counter.
When using API    /api/v1/organizers/(organizer)/events/(event)/quotas/(id)/availability/ on unlimited quota, paid orders counter (and all counters) is not set and can't be retrieved.

I'm not python dev, but I think it's because of early return in method _compute(self, quotas, now_dt).
If _early_out is set to true (default value) counters are not calculated (according pydoc)
When using API, this flag can't be forced to False
(cf src/pretix/api/views/item.py, method def availability(self, request, *args, **kwargs)

**Comment by raphaelm** [comment]
Thank you for raising this. I'm not yet sure if it's something we want to fix, since for unlimited quota, there should be no need to figure out how they've been used, as they're always available. I agree that it is a little inconsistent, yes, but changing it would prevent us serving these responses from cache, which might be expensive, depending on how people use it.

**Comment by rapinf** [comment]
Thank you for this quick response. 
There is another way to get paid orders number? 
(this information is displayed in pretix in back office when you consult the subevents)
![capture](https://user-images.githubusercontent.com/66670218/149365613-b599a689-da9d-4c6e-80c0-e5bc23c96137.png)

**Comment by raphaelm** [comment]
The API doens't currently expose good ways to get statistical values, unfortunately. :(
