### ISSUE TITLE
Internal Server Error while using MySQL sql_mode=only_full_group_by

### ISSUE THREAD

**Issue by nilskamm** [pretix/pretix#2437]
**Describe the bug**
When trying to open one event it shows an Internal Server Error.
The pretix.log shows 4 times this error:
(1055, "Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'pretix.pretixbase_orderposition.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")

**Expected behavior**
When trying to open an event it should open without an internal error

**Screenshots**
![internal_error](https://user-images.githubusercontent.com/75222264/151785390-266369ad-5fa4-4fb9-8a3b-b6c5babbc80b.PNG)

**Additional context**
MySQL-Version: mysql  Ver 8.0.28 for Linux on x86_64 (MySQL Community Server - GPL)
This problem only appears with our second event, which was working fine until we created some products.
There are no orders yet. 
Our first event is still working fine. 
When we deactivate the sql_mode "ONLY_FULL_GROUP_BY" the second event also works fine but we don´t want to have this mode deactivated in live environment. 
Attached is our pretix.log and the mysql-query.log from the time the error happens:
[mysql-query.log](https://github.com/pretix/pretix/files/7970344/mysql-query.log)
[pretix.log](https://github.com/pretix/pretix/files/7970345/pretix.log)

It looks like it just needs some adjustment on these mysql queries and it would work fine.

**Comment by raphaelm** [comment]
Is there any reason you don't want to deactivate ONLY_FULL_GROUP_BY?

Unless there is a really really good reason, we're not going to fix this since an easy workaround exists and we don't want to make our queries more complicated to deal with MySQL specifically if we don't need to. (In the long run, we want to deprecate MySQL support anyways.)

**Comment by nilskamm** [comment]
It is one of the activated modes which is activated by default when 8.0 is shipped. So this error should also hit others who use MySQL. We also have other software using the same database as well but i totally get, that you don´t want to "waste time" when you don´t want to support MySQL in future versions.

Do you already know when you want to deprecate MySQL?
Will you still support MariaDB or shall it be PostgreSQL only?

**Comment by raphaelm** [comment]
> It is one of the activated modes which is activated by default when 8.0 is shipped. So this error should also hit others who use MySQL. 

Okay, thanks. So there is no explicit reason it needs to be turned on, but we should add it to our installation documentation!

> Do you already know when you want to deprecate MySQL?
> Will you still support MariaDB or shall it be PostgreSQL only?

Nothing is decided yet. I personally want to go PostgreSQL-only at some point, since it will allow us some features to be built much more easily. It will certainly not happen in the next 6 months, and it will have a long announcement period, migration instructions, etc, if we do it.

**Comment by nilskamm** [comment]
Thanks a lot!
Yes there is no explicit reason i can point out right now.
To have this information in the documentation would be nice.

And thank you for the information about future usage. 
I will check out PostegreSQL.
