### ISSUE TITLE
Error in single exporter form collapses all exporters

### ISSUE THREAD

**Issue by MaicoTimmerman** [pretix/pretix#2542]
**Describe the bug**
When submitting the "checkinlistpdf" exporter, without a check-in list present, an error is created on all of the available forms. Due to the presence of the error on all forms, all exporters are shown, making it very confusing to see the actual problem with the exporter in use.

I've located https://github.com/pretix/pretix/commit/488273d5f2abd91910e89f01eae15ccf96d325a6 to introduce the current behaviour, however I'm not sure why the forms which were not submitted also render with `.has-error` on it's fields. 

**Expected behavior**
To have all exporters be closed, except for the one submitted.

**Screenshots**
![scrot-2022-03-17T17:54:06+01:00](https://user-images.githubusercontent.com/904824/158856244-9e848a25-54d8-49e9-b7d4-356d3c257f18.png)

**Additional context**
-

**Comment by wiffbi** [comment]
This bug has multiple levels. First it fills all exporterForms with POST-data without looking which exporter was selected. This makes it so that all forms are validated and get marked as having errors. Second, the JavaScript to open the `<details>` with forms that have errors seems to have a problem as well. I will look into this.

**Comment by wiffbi** [comment]
The problem wasn’t in thte JS, but in the template. Fix is on the way.
