### ISSUE TITLE
Ticket return only possible for whole order

### ISSUE THREAD

**Issue by lumsel-lt** [pretix/pretix#2598]
**Ticket return only possible for whole order**

In an order of multiple tickets, only one needs to be canceled. Currently, only all tickets of an order can be returned. 

The issue is, that with returning all tickets of an order the waiting list immediately gets triggered and all returned tickets get offered to someone else. There is no possibility to intervene the process and therefore sell the original customer the needed amount of tickets back. 

**Expected behavior**

It should be possible to return only a defined amount of tickets for an order. 
If this is not wanted/ possible an option should be offered to resell the same customer the number of tickets he actually needs in the process of return.

**Comment by raphaelm** [comment]
It is intentional that partial cancellations are not supported for the end user but only through the backend.

There are too many situations where partial cancellations would cause lots of very complex issues. For example, if there is a group discount that you get 20% off if you register 5+ tickets, and someone does partial cancellations down to 4, the pricing for the other ones would need to change retroactively, which is almost impossible to do correctly for all situations (this is only one example of the many things that need to be thought of here).

In most events, partial cancellations are not so common that it is a problem that you need to write an email to the event organizer for this. In the backend, it can be easily done and orders can also be splitted.

A "resell tickets" feature is also a huge undertaking and currently out of scope for pretix.

**Comment by lumsel-lt** [comment]
Hello Raphael,

thanks for the quick reply and sorry for my late reply. ;) 

I can see the point why not to implement this. Good to know that it is possible in the backend - I'll have a look into that. 

Kind regards
Luca

**Comment by AlexanderWillner** [comment]
> There are too many situations where partial cancellations would cause lots of very complex issues. 

The main blocker seems to be the wide range of edge cases that partial cancellations introduce.
Do you have any early design notes or drafts that outline what would be required to support this feature?
Our use case involves free events only, so the financial and refund-related parts don’t apply, which should simplify the overall scope.

**Comment by AlexanderWillner** [comment]
#4695

**Comment by AlexanderWillner** [comment]
@raphaelm feel free to re-open this issue in case my changes go in the right direction
