### ISSUE TITLE
Order overview: Improve columns

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#302]
The labels of the columns are unclear and should be improved, maybe with explaining tooltips. Also, a reordering of the columns could help.

**Comment by rixx** [comment]
Ideas:

 - Remove 'cancelled' column, it's only irritating
 - Hence, rename 'Total (pending and paid)' to 'Total'
 - Move 'Total' to the far right, because that's where you would commonly expect the columns summing everything up?
 - Different highlighting for the last row, or at least a thick line in between. As is, it does not differ from category sums
 - Folding categories seems cool to me, but probably isn't that useful in reality
 - Rename the heading to "Order position overview" or "Sales overview" since the numbers are not actual orders

What'd I miss?

**Comment by raphaelm** [comment]
> Remove 'cancelled' column, it's only irritating

I'm unsure here, that is an important metric.

> Hence, rename 'Total (pending and paid)' to 'Total'

If we remove cancelled and call the other thing total, we still have refunded in there. Do we want that? Refunded is an even more important metric than cancelled.

> Move 'Total' to the far right, because that's where you would commonly expect the columns summing everything up?

Agreed

> Different highlighting for the last row, or at least a thick line in between. As is, it does not differ from category sums

Agreed

> Folding categories seems cool to me, but probably isn't that useful in reality

Folding items with lots of variations seems useful, categories not so much.

> Rename the heading to "Order position overview" or "Sales overview" since the numbers are not actual orders

Nice! This could improve #291 as well

**Comment by rixx** [comment]
Okay, agreed. How about
```
canceled | refunded |      purchased         |
---------|----------| pending | paid | total |
```
With thinner lines between pending, paid and total?

**Comment by raphaelm** [comment]
I like that a lot!

**Comment by loelkes** [comment]
Please do add a columns with he currently set quotas. This is pure usability feature request so I do not have to look on two separate pages to get the overview of my orders.
