### ISSUE TITLE
Do not send links that allow to download tickets without further authentication in unencrypted emails

### ISSUE THREAD

**Issue by tyll** [pretix/pretix#350]
For the 33C3 the installed pretix instance sent unencrypted e-mails that contains links to download tickets without further authentication. Therefore anyone with access to these e-mails can download the respective tickets without the actual buyers noticing. Therefore it would be better from a security perspective to just notify users that they can download their tickets now after authenticating to the ticket shop again. Additionally if #319 is implemented, the tickets could be send in encrypted e-mails instead.

**Comment by rixx** [comment]
> to just notify users that they can download their tickets now after authenticating to the ticket shop again.

Authenticating how?

> Additionally if #319 is implemented, the tickets could be send in encrypted e-mails instead.

For people with a working PGP setup, that is.

**Comment by raphaelm** [comment]
Hi,

thanks for your feedback! 

1. The "hey, your ticket is available" mail does not make a difference as the very same URL is already in the "your order has been placed" and the "we received your payment" emails.

2. There is no authentication for buyers in pretix. We had that in the original design, but we've thrown it out because it added a bunch of complexity to the checkout process and a raised lot of UX issues. Additionally, experience from past CCC events with a different software shows that lots of people are not even capable of remembering their username, let alone their password. The "just click a link" approach works well in terms of reducing support cases on this topic.

As always, this is a though trade-off between security and usuability. In this case, I believe the usuability is worth the reduced security.

Best
Raphael
