### ISSUE TITLE
sendmail: reminders 1 day-before-event are sent for orders made on the day of the event

### ISSUE THREAD

**Issue by stapelberg** [pretix/pretix#3757]
### Problem and impact

We have configured an email reminder using the sendmail plugin, to be sent out 1 day before the start of the event.

This works fine for orders that come in before the reminder should go out.

But for orders that come in afterwards (e.g. on the day of the event), the reminders are unexpectedly also sent!

The reason is that the sendmail plugin uses a sliding 2-day window for reliability: https://github.com/pretix/pretix/blob/6c479808d0b931653296a408ea620dbbafda214d/src/pretix/plugins/sendmail/signals.py#L161-L173

### Expected behaviour

Reminders should not be sent for orders that are made after the configured reminder time.

Maybe we could check if the order timestamp is more recent than the scheduled mail date?

**Comment by stapelberg** [comment]
Thanks for the explanation. I had another look and realized that there is another condition that I had previously missed: reminders are sent spuriously when the subevent is created the day of the subevent (ScheduledMail is “planned”) and then immediately receives an order. The next cron iteration comes along and sends the reminder.

I just tested this series of events in my test instance and was able to reproduce the behavior.

**Comment by raphaelm** [comment]
This description makes sense, but I'm not sure I agree it's a problem, plus, it only occurs if the cronjob is unreliable in the first place, or am I missing something there?

**Comment by stapelberg** [comment]
> it only occurs if the cronjob is unreliable in the first place, or am I missing something there?

No, I don’t think that’s correct. For me, it happens every time, and our cronjob is working correctly.

> This description makes sense, but I'm not sure I agree it's a problem

We can certainly live with it. Feel free to close the issue if you think it’s not worth fixing.

Happy new year!

**Comment by raphaelm** [comment]
Ah okay, I think I may have not understood it correctly, I focused too much on the time the order comes in, not the creation of the invoice. So the situation is e.g.:

- You have configured a reminder to be sent out one day before event
- You create a subevent for Sunday afternoon on Sunday at 8
- An order comes in immediately after you created the subevent, but before the cronjob marked the email job as done (i.e. 5-10min window)

Correct?

Then yes, adding the order timestamp into the filter would fix this, but would cause different behaviour on delayed cronjob execution (because *some* orders would get the email, which one could argue as both correct and wrong, I guess).

Another solution could be just triggering the mail to run immediately after subevent creation, correct?

**Comment by stapelberg** [comment]
Yes, I think you got the order of events correct, and yes, I think triggering the mail run immediately after subevent creation sounds like a good idea.

That said, I’ll close this issue because we have since moved all email sending away from pretix and into our own frontend, which gives us a lot more control and flexibility. So our need for this is gone, and I’ll let someone else reopen if they ever run into the same problem :)
