### ISSUE TITLE
Add logo to event organizers

### ISSUE THREAD

**Issue by jfwiebe** [pretix/pretix#379]
What's about adding a "logo" attribute to event organizers (similar to events) which is displayed on the front page of each event organizer?

**Comment by jfwiebe** [comment]
(maybe even something like main color, similar to events)

**Comment by raphaelm** [comment]
We have very few organizer-based settings, because that was not much of a priority to me so far, but I'd sure take pull requests :)

**Comment by b-lawrence** [comment]
Hi guys,

I'm new to the project. Happy to contribute. Looks like I'll be taking a crack on this one. I believe this should set me going in the right direction. 😄

**Comment by raphaelm** [comment]
Thank you very much! :) If you have any questions just ask!

**Comment by b-lawrence** [comment]
Sure thing @raphaelm. From what I understand so far, we need to allow `event organizers` add logos to their organizer pages, and maybe a full-width banner to sit on (something that represents the `organizer's' theme`)? Also, maybe we could do the same for `events` because I noticed events don't have that feature as well. Am I understanding this correctly?

**Comment by raphaelm** [comment]
Yes. Let's go for the logo first in a similar way that we currently have event logos. 

Once that works, if that's an area that you are interested in, I'd be happy to explore options to allow more custom styling together with you. 

Currently we have logos (that can in theory be a full-width banner) and custom primary colors. However, it would be nice if even more theme customization was possible, I totally agree. It probably will not be that simple if we want to keep security and accessibility high, but I'm sure there are some things that can be improved.

**Comment by b-lawrence** [comment]
Sounds good. Getting right to it. 😄

**Comment by b-lawrence** [comment]
Looks like I'm missing a `pretix.cfg` file. I presume that's the highly confidential project's config file? I have been testing using the default DB (sqlite3).

**Comment by rixx** [comment]
The `pretix.cfg` structure is detailed [here](https://docs.pretix.eu/en/latest/admin/config.html), development specific settings are mentioned [here](https://docs.pretix.eu/en/latest/development/setup.html?#working-with-mails). Hope this helps :)

**Comment by raphaelm** [comment]
Why do you think you are missing it? :) Most development work *should* be possible without one.

**Comment by b-lawrence** [comment]
@raphaelm yeah you're right. It would not matter anyway since there are fallback options along the way in `settings.py`. Thanks @rixx, that would come in handy.

Right now, I'm getting this weird error:

```
django.db.utils.OperationalError: no such table: pretixmultidomain_knowndomain
```

I've tried resyncing my DB, making migrations, and re-migrating. None seems to work.

**Comment by b-lawrence** [comment]
Works now. Had to`rm` my local SQLite DB, and then added it again.

**Comment by raphaelm** [comment]
Okay, strange :( Glad to hear it works now.

**Comment by b-lawrence** [comment]
Guys, what would be the best way to persist the `logo_image` value from the organizer's update form using the `OrganizerSetting` model? I noticed that these models(GlobalSetting, OrganizerSetting, EventSetting) are being used site-wide to hold key-value pairs of relevant data related to each entity. Since the `OrganizerUpdate` view class is using an `UpdateView`, would it be wise to create an extra attribute on the `Organizer` model or just use the already existing `OrganizerSetting` model?

**Comment by raphaelm** [comment]
The ``OrganizerSetting`` can also hold a file as a value (though it is a bit of a hack), so we can use this, but yes, this will require that ``OrganizerUpdate`` contains *both* a ``ModelForm`` and a ``SettingsForm``. You can just look at ``EventUpdate`` and copy from there -- it does exactly the same thing ;)

**Comment by b-lawrence** [comment]
"The OrganizerSetting can also hold a file as a value (though it is a bit of a hack)" -> yeah I figured :). Thanks a lot! This'll do.
