### ISSUE TITLE
Makemessages does things

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#383]
When issuing the other pull request, I noticed that `makemessages` produced unexpected (to me) output, specifically regarding the `helpers` directory. I couldn't make sure at a glance why this was and if it was intended. I made sure my dependencies were up to date.

PR is attached to show the results of makemessages if committed as produced. Please review.

**Comment by raphaelm** [comment]
I believe this is why the ``Makefile`` calls ``./manage.py makemessages --all --ignore "pretix/helpers/*"``. But maybe we can even get rid of this and handle this otherwise, so I'll leave this open for now.

The complication with the helpers directory is that it stores the ``de_Informal`` translation of Django itself which is a pretty non-standard thing to do.

**Comment by rixx** [comment]
Oh. Haven't gotten used to the `Makefile` yet.

**Comment by ZEROF** [comment]
I will share my solution:

Add to travis file:

install:
    - pip install -U pip wheel setuptools==28.6.1
    - apt-get install gettext

I don't use travis, i use shippable, but same config will work ;). Now i have some other error on last build step, but if i don't find solution i will open new issue.

**Comment by raphaelm** [comment]
Hi @ZEROF :) That is not the problem that rixx was having but thanks for your comment anyways! If you see ways in which we can improve the documentation or if you get stuck, please open an issue! :)

**Comment by ZEROF** [comment]
Yep, i saw to late :). Anyway, now build on shippable is working, i will share tip with others.
