### ISSUE TITLE
Use appropriate interval for revenue over time

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#388]
In the statistics view, when your presale is longer-running (spanning, say, six to twelve month), having each day as a data point on the "Revenue over time" chart is overkill and makes the graph consist mostly of bullets … scaling down to alternate days (… every other day, one out of three …) dynamically would be nice here, I think.

**Comment by danlls** [comment]
The bullets can be easily removed by setting `pointSize: 0`, IMHO, I think having each day as data point is fine if the bullet isn't there.

As I've suggested in https://github.com/pretix/pretix/issues/387#issuecomment-319902137, it would be nice to show results from event `start_date` to `now` for revenue as well.

I can fix this too, let me know what you think! 😄

**Comment by rixx** [comment]
Not having bullets is probably the best thing to do, :+1:

**Comment by raphaelm** [comment]
I'm not happy with having the revenue chart behave differently than the order chart. I believe there should be one fat switch between "daily/weekly/monthly" or and maybe even a time slicer "date from/to" on top of the statistics page that should affect *all* statistics. Deciding for or against the bullet point could then be done based on the number of data points (because I think the bullet is really helpful if there are few of them). I think I'll close this as a duplicate to #387 then
