### ISSUE TITLE
Offer ical link/export for events

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#389]
Many events offer ical links - generating one from an event data automatically would be nice.

**Comment by raphaelm** [comment]
Is best done after #381

**Comment by jlwt90** [comment]
Hello, can i take this enhancement ticket?

I am planning to add the ical link to the event page.
http://localhost:8000/bigevents/xxxxxxx/

The link will dynamically generate an .ics file for download, e.g. 
http://www.pratie.com/lab/icalendar/

does it look good?

**Comment by raphaelm** [comment]
Sure, go ahead! :) I believe the [icalendar](https://pypi.python.org/pypi/icalendar) package might be helpful to generate the file.

**Comment by jlwt90** [comment]
@raphaelm sorry for the late. I am pretty new to django. Could you please give me some comments on the changes? 
https://github.com/jlwt90/pretix/commit/16bd3ccc3f8bb8115de02797e3039d0b39d5f5ef

I added a link on event index page which sends a GET request to url <organizer>/<event>/download . The EventDownload view will then create a CacheFile using icalendar library and return a FileResponse object. 

Thanks! :)

**Comment by raphaelm** [comment]
Hi @jlwt90 no problem at all! Next time just create a pull request, that makes it easier to leave comments and discuss the changes. Overall, this looks very good! Thank you! I have two comments to beginn with:

* Could you name it ``EventIcalDownload`` instead of ``EventDownload`` and the URL ``/ical`` instead of ``/download``? Because you are downloading an ical, not an event, so this would be clearer :)
* You don't need to create a ``CachedFile``  here, that is only unneccesary work. Just drop that and directly output the ical :)

If any of this is unclear, feel free to ask!
