### ISSUE TITLE
Event-independent callback URLs for payment providers

### ISSUE THREAD

**Issue by jfwiebe** [pretix/pretix#429]
Hi!
At the moment, It seems like that each event has its own callback url for e.g. paypal or stripe. wouldn't it be great to have one central url where the callback needs to be placed? At the moment you have to (or it seems like) add a new callback url at each payment provider for each event.

PS: I am not sure if a callback delivered to /organizer/event_a but with information regarding a transaction for event_b is processed regardless of the url, but from a users perspective, if you read the tooltips, it feels like that it won't process correctly.

Thanks!
Jan Felix

**Comment by raphaelm** [comment]
Hi!

I understand why this is useful, but this is highly non-trivial. It used to be different but it is the way it is for two reasons. The first is that at the CCC installation, all non-event-related views are not accessible from the public network, so it needed to be an event-related view. 😉 The second reason goes a lot deeper:

* Webhook calls from most payment providers are unauthenticated POST requests, i.e. *anyone* could send them. PayPal supports a very complicated signing scheme, but Stripe does not.
* Therefore, we cannot really trust any meta data within the POST request. What we do instead, is ignore everything except the payment ID and use that ID to get the current payment status from the payment provider's API.
* In order to connect to the API, we need API credentials – which can be different for every event! So we need to know the event first which is not obvious from the meta data in the web hook e.g. in PayPal's case.

I'm not saying its impossible to change this, e.g. with a better internal mapping of payment IDs to orders (and therefore events), this could be improved. But it is not an easy improvement and one that has to be evaluated very carefully in terms of security.

There is a general wish from some organizers to move some settings (i.e. API credentials) from the event level to the organizer level. While this is easy from in data model, I don't see a good way to do it UI-wise.

> PS: I am not sure if a callback delivered to /organizer/event_a but with information regarding a transaction for event_b is processed regardless of the url

No, it won't be, for the reasons above.

Cheers
Raphael

P.S.: If you don't mind, please try to use a more gender-inclusive greeting than "Hi guys!" when adressing a group in the tech world ;)

**Comment by jfwiebe** [comment]
Hi!
First: Sorry for the greeting - of course I want to adress everyone who is reading this!

Yeha, thanks for the great explaination. I totally understood the point you are saying and it sounds hard to make it fit for all purposes in which people will use pretix. 

> There is a general wish from some organizers to move some settings (i.e. API credentials) from the event level to the organizer level. While this is easy from in data model, I don't see a good way to do it UI-wise.

Same as above. I can only imagine something like a checkbox stating "overwrite organizer's settings", but it will be hard to implement because of the reasons you stated before.

Best regards!
JF

**Comment by raphaelm** [comment]
> First: Sorry for the greeting - of course I want to adress everyone who is reading this!

No offense taken, just wanted to note it ;)

**Comment by raphaelm** [comment]
This is fixed, in 1.5.x the callback URLs will be event-independent (see 5f529817 and 1d2d9d8b)

However, we strongly recommend keeping the webhooks for past events in place as long as you want to receive events fro them, since only events for payments created with 1.5.x will be properly recognized by the new URL.
