### ISSUE TITLE
re-authentication form (reauth) links to /control/logout without carrying ?next= parameter

### ISSUE THREAD

**Issue by stapelberg** [pretix/pretix#4492]
### Problem and impact

After a period of inactivity, pretix prompts me for re-authentication. For example, pretix redirects me to a URL like `https://pretix.example.net/control/reauth/?next=/control/event/orga/myevent/quotas/`

The “continue” button does not seem to work with the pretix-oidc plugin I’m using (reported at https://github.com/thegcat/pretix-oidc/issues/2), so I regularly use the “log in as someone else” button. This button links to /control/logout, without the `?next=` parameter, meaning I will not end up on the page that I originally wanted to open.

### Expected behaviour

I would have expected the button to include a `?next=` parameter so that I end up on the correct page after logging in again.

### Steps to reproduce

1. Open `https://pretix.example.net/control/reauth/?next=/control/event/orga/myevent/quotas/`
2. Click “log in as someone else”
3. Observe how you don’t end up on the /control/event/orga/myevent/quotas/ page

### Screenshots

![2024-09-28-pretix-reauth](https://github.com/user-attachments/assets/625dbfb4-45b4-43b3-8dd2-52dea14c778b)

### Version

2024.8

**Comment by thegcat** [comment]
Is it possible that because the OIDC Callback URL (or any auth plugin callback URL for that matter) is not exempted from the reauth check in https://github.com/pretix/pretix/blob/master/src/pretix/control/middleware.py#L138 it is currently not possible to reauth using those schemes?

For context, the OIDC plugin currently does not carry over the `next` parameter, but I'd at least expect the reauth to bring you back to the overview page.

**Comment by stapelberg** [comment]
Let’s keep the discussion as to why reauth doesn’t work over in https://github.com/thegcat/pretix-oidc/issues/2, and keep this issue focused on the missing ?next parameter in the reauth form :)

**Comment by raphaelm** [comment]
I wonder if a "I am someone else" link *should* carry a ?next= parameter, which  – with some likelihood – will end in a 403/404 if you that "someone else" has no access to the same resource. Seeing a 403/404 directly after login is certainly weird and will feel like abug.

Since you are not someone else, fixing the actual reauth does sound like the more proper course of action to me?

**Comment by stapelberg** [comment]
> I wonder if a "I am someone else" link _should_ carry a ?next= parameter, which – with some likelihood – will end in a 403/404 if you that "someone else" has no access to the same resource. 

Yes, there is a chance that a different account has no access. But I don’t know why the likelihood for that case would be any higher than for the opposite case, where you do have access to the resource, just with multiple accounts. 

To me, honoring the user’s stated intent (open resource X, show a login form for it) is more important than guessing as to what could happen.

> Seeing a 403/404 directly after login is certainly weird and will feel like a bug.

Sure, but you’re not seeing a 403/404 after just *any login*, you’re seeing it because you explicitly tried to request a resource you don’t have access to. To me, that’s exactly the expectation. 

> Since you are not someone else, fixing the actual reauth does sound like the more proper course of action to me?

Yes, that of course is the better option. Fixing the next= parameter just seemed like an easy thing to also improve while we’re waiting for a proper fix :)

Maybe yet another option would be to make the reauth feature configurable? For us, it’s certainly rather annoying — we have our SSO system configured to reauth every day, but we don’t want to be interrupted with authentication during the day.

**Comment by raphaelm** [comment]
I think I'll close this as #4498 is on the verge of being fixed and therefore the immediate need for this will hopefully be over with the next release, and we can avoid the discussion about whether a ?next here is right or wrong
