### ISSUE TITLE
Make configuration path configurable

### ISSUE THREAD

**Issue by pennylane0815** [pretix/pretix#528]
The configuration path /etc/pretix/pretix.cfg seems to be hardcoded.
As I am currently trying to install pretix on FreeBSD, where all user configuration is done in /user/local/etc, I placed the pretix configuration in /usr/local/etc/pretix. 
It did not use my configuration until i symlinked /usr/local/etc/pretix to /etc/pretix.
Having a --config flag or similar would greatly enhance that experience!

**Comment by raphaelm** [comment]
A --config flag would be impractical in many situations (we'd somehow need to integrate it into various commands of django), but it would totally merge an option to override the config file location by an environment variable.

**Comment by Volcyy** [comment]
Hello!
I'd be interested in this issue, but looking at the [source code of settings.py](https://github.com/pretix/pretix/blob/master/src/pretix/settings.py#L15-L20) it appears that if an environment variable `PRETIX_CONFIG_FILE` is set, it is used instead of the default of `/etc/pretix/pretix.cfg`. 

Would a documentation update be needed, mainly in [config.rst](https://github.com/pretix/pretix/blob/master/doc/admin/config.rst)?

**Comment by raphaelm** [comment]
Oops. You totally caught me. Yep, a documentation update would be what is needed then. :D
