### ISSUE TITLE
Provide settings <legend> headings with id attributes

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#593]
The pretix settings are fairly extensive and on some pages, you have to scroll quite a bit to reach the setting you are looking for. Formatting the headings like this:

    <legend id="waiting-list">{% trans "Waiting list" %}</legend>

would allow to refer to a specific heading by the `#waiting-list` fragment at the end of a URL.

**Comment by SanketDG** [comment]
Hi, interested in taking this up.

Instead of going the manual terse way of editing each html file, how about using a custom template tag to generate the whole `<legend>...</legend>`? I would pass the name, which would be slugified in the `id` attribute.

**Comment by raphaelm** [comment]
@SanketDG Sure, go ahead. I'm not sure if a custom template tag is worth it, since it *still* involves editing all HTML files manually and inserting the ``id=""`` attribute does not make the code that much more maintainable. But there are also more downsines to automatic sluggifying: (a) The slugs should if possible never change, even if the text changes in the future and (b) The slugs should be always english, while the text varies with the user language.

**Comment by raphaelm** [comment]
This happens kinda implicitly with our new tabbed settings
