### ISSUE TITLE
API to buy tickets

### ISSUE THREAD

**Issue by sylvinus** [pretix/pretix#599]
Hello,

I was happy to see the new REST API!

I'm going to need to be able to buy tickets via the API. (Payment would not go through Pretix but I'd still need to create orders in Pretix & mark them as paid).

I'm planning to implement it in the next few days and will submit a PR if there's any interest here. Regardless, it would be very helpful to have feedback on my implementation plan:

1. Add 2 new API calls in `pretix/api`: `CreateOrder` and `MarkOrderPaid`
2. In `CreateOrder`: generate a new random cart_id, call `base.services.cart.add_items_to_cart` and `base.services.cart.set_cart_addons` with data from the `POST` request, then call `base.services.orders._perform_order` with `payment_provider="banktransfer"`. Return the `order.id` to the client.
3. Once the client has made the payment on our side, use `MarkOrderPaid`: get the order ID from the `POST` request, then call `base.services.orders.mark_order_paid`

Would that be a good way to go?

Thanks!

**Comment by raphaelm** [comment]
Hi @sylvinus!

> I'm going to need to be able to buy tickets via the API.

You just chose the single most complicated feature imaginable to build for the API as a starter. Don't get me wrong, I'd **love** to see this feature and I'd love to get such a pull request, but it will be quite an effort to polish that well enough. I would strongly suggest to implement the "mark order paid" API call first and the order creation second, just because it is a lot easier and will make it easier to get into how the API works and how to integrate it well.

Your implementation plan seems like a useful approach. Here's what I think needs to be done:

## Create order

This should somehow become a ``PUT`` request to the ``/api/v1/organizers/bigevents/events/sampleconf/orders/`` endpoint. After giving it some thought, I believe your idea to just go via ``add_items_to_cart`` and ``set_cart_addons`` is actually a good approach, but there are some things making it less trivial than it seems:

* Both ``add_items_to_cart`` and ``set_cart_addons`` can fail in hundreds of ways because of invalid input or system state (invalid combination, sold out, invalid voucher, ...). In some of these cases, there will still remain some items in the cart. That's useful if you are a real user that will see the cart again and "work on it". In this case, we need to deal with proper cleanup, so no half-baked carts stay in the process.

* There's more to it than just products and add-ons:
    * An email address is required for every order, but there can also be [different fields required by plugins](https://docs.pretix.eu/en/latest/development/api/general.html#pretix.presale.signals.contact_form_fields) that hook into the ``pretix.presale.forms.checkout.ContactForm``. Somehow, those fields would also need to be exposed via the API such that they can be filled and, more importantly, validated. The data for this fields is then included in the ``meta_info`` attribute of the order.
    * There is complex validation logic for invoice addresses in ``presale.forms.checkout.InvoiceAddressForm`` that will get even more complex in #559. This would need to be refactored in some way to avoid duplicate code.
    * Depending on the event settings, for every ticket a name and email address might be possible or even required to fill in. Also, custom questions come with non-trivial validation logic that is currently only present in ``presale.forms.checkout.QuestionsForm``.
    * In that ``QuestionForm``, again, plugins can [hook in to add additional fields](https://docs.pretix.eu/en/latest/development/api/general.html#pretix.presale.signals.question_form_fields) with custom validation rules. The data for this fields is then included in the ``meta_info`` attributes.
    * There is even a (currently undocumented) plugin hook ``checkout_flow_steps`` that allows to add whole pages of new functionality into the checkout process. If we can also create orders via the API, we should add a new plugin hook to perform additional validation etc. on the input such that plugins can replicate their behaviour in some way.

That *should* be most of it, but there might be more to it.

For now, I think it is okay to just pass a payment provider as the input but leave all orders created this way unpaid and have the second API call you suggested -- processing real payments would require a different kind of interaction. It should be possible to specify any payment provider, not only banktransfer. In that case, the order will appear like a "failed" credit card transaction that still needs to be completed, which might be an intended use case.

In my eyes, step number one would be to propose a format for the input that should be sent to the endpoint, as this will be the most important part of the API design to get right because we won't be able to easily change it in the future.

## Mark order paid

This should be implemented as something like
```
POST /api/v1/organizers/bigevents/events/sampleconf/orders/ABC12/mark_paid/
```
with an empty body, so it should be a [custom detail route](http://www.django-rest-framework.org/api-guide/viewsets/#marking-extra-actions-for-routing) on the ``OrderViewSet`` class. The implementation could be relatively straight-forward (untested draft):
```
@detail_route(methods=['post'])
def mark_paid(self, request, **kwargs):
    order = self.get_object()
    if self.order.status not in (Order.STATUS_PENDING, Order.STATUS_EXPIRED):
        # raise error 400 with useful message
    try:
        mark_order_paid(self.order, manual=True, user=self.request.user)
    except Quota.QuotaExceededException as e:
        # not sure which code to raise here, either 400 or 409 or 403 with useful message
    except SendMailException:
        # probably return 200 anyway?
    else:
        # return 200 with new state of the order object
```

**Comment by sylvinus** [comment]
Thanks a lot @raphaelm for the pointers!! Very helpful.

Doing a PR fully compatible with all the features of Pretix indeed seems very complicated. My usecase is much narrower as I'm not using all the features so there are many shortcuts I can take. I'm still happy sharing the experience here, it might help implementing the full-blown API in the future, and hopefully have a nice public showcase of the API :)

I have a first prototype of `CreateOrder` working. However as I was looking into hooking up stripe, I realized I would duplicate most of the server-side code already implemented in the stripe module. So my new approach would be to only pass the stripe token (which we get after their Checkout flow) to the API, and have the charge/webhooks work as usual.

One issue I saw is that the code in `plugins/stripe/payment.py` is pretty coupled to the `request` object. If I were to use this, using the `request` object from the API call wouldn't make any sense I guess, so the best way may be to mock a fake `request` object? 

I don't know about the project goals, but it might be interesting to think about the future write API so that the whole presale module could be reimplemented on top of it (which is what we're basically doing with a much smaller feature set).

Thanks!

**Comment by raphaelm** [comment]
Sorry for the late reply :)

> Doing a PR fully compatible with all the features of Pretix indeed seems very complicated. My usecase is much narrower as I'm not using all the features so there are many shortcuts I can take. I'm still happy sharing the experience here, it might help implementing the full-blown API in the future, and hopefully have a nice public showcase of the API :)

That's what I expected :( I obviously hoped to get a full PR, but didn't really expect it ;)

> One issue I saw is that the code in plugins/stripe/payment.py is pretty coupled to the request object. If I were to use this, using the request object from the API call wouldn't make any sense I guess, so the best way may be to mock a fake request object?

Using a fake request object would be an hack that works, but wouldn't be a good option in the long term. A good, stripe-specific solution would be to create private methods on the ``Stripe`` class that only operate on the level of strings like the payment token and have those methods called by the methods operating on the request objects. Your API could then call the private methods directly.

Refactoring the whole payment API away from requests will be hard, since some payment providers like PayPal really hook into the request-response-flow by redirecting the user somewhere else etc.

> I don't know about the project goals, but it might be interesting to think about the future write API so that the whole presale module could be reimplemented on top of it (which is what we're basically doing with a much smaller feature set).

Having a complete API is totally one of our goals! Implementing the whole presale module on top of it would only be possible on a certain level somewhere in the middle of the stack, since the presale module is supposed to work for users with JavaScript turned of, but still, of course we want to avoid duplicate code paths.

**Comment by raphaelm** [comment]
With the new fields added to this API: https://docs.pretix.eu/en/latest/api/resources/orders.html#creating-orders and 
And the new processes described here: https://docs.pretix.eu/en/latest/api/guides/custom_checkout.html

it should be possible to drop your custom API at some point and use the official one, @sylvinus

**Comment by sylvinus** [comment]
Awesome! That would indeed be much cleaner. 

BTW, we've just updated to pretix 3.0 and did some more patches for stripe SCA. We didn't want to use elements so we wrote a new plugin for stripe checkout. I'll send the patch to you by email soon so you can have a look.

thanks!
