### ISSUE TITLE
Render release version

### ISSUE THREAD

**Issue by johnjohndoe** [pretix/pretix#607]
When users file issues it might be valuable for you to know the **software version** which they are using to analyze the source of the problem. Therefore, please render the release version both in the **website** and in the **administration backend**.

**Comment by rixx** [comment]
I can see that this would be useful for the administrator, but I cannot imagine that it would be terribly useful or pretty in the frontend.

**Comment by raphaelm** [comment]
While it is already displayed for system administrators, it is not visible for event organizers. I'm unsure here, because it is potentially dangerous because it very directly leaks which security vulnerabilities might be unfixed in the deployed version.

(Also, since I know Tobias is using pretix.eu, it would only be useful that much because it'd show something like ``1.7.0.dev0`` right now all the time.)

**Comment by johnjohndoe** [comment]
I saw you also showing the revision in the docs.

![pretix-docs-footer](https://user-images.githubusercontent.com/144518/29748065-b98a5a94-8b0d-11e7-84b2-feec24865fb2.png)


I think it would be useful to show the version and revision (Git hash) for administrators. Here is a mockup how it could look like:

![pretix-version-mockup](https://user-images.githubusercontent.com/144518/29748043-4b73ce82-8b0d-11e7-9512-809af6c21fbf.png)

**Comment by raphaelm** [comment]
I'll close this for now, because I'm decided that this will not happen, at least not in production installations. The reason is simply that my data suggests that unfortunately many pretix installations are not quickly updated when new versions are released. In case of security vulnerabilities or exploitable bugs I wouldn't want to expose which installations are already patched and which are not too easily, especially not to logged-out users.

The docs show it, yes, but they are always built from the latest git master branch and don't pose a security risk in this sense.

**Comment by johnjohndoe** [comment]
Okay. Thanks. I hope _security by obscurity_ does not get one's revenge. 😈

**Comment by raphaelm** [comment]
We'll do our best to do the right security decisions wherever possible and security by obscurity is certanly not the way to go :wink: However, internet-wide scans for vulnerable web software versions are a thing and I believe it is more than just security by obscurity to make their job harder. I'm aware that software version fingerprinting exists and it is probably easy to fingerprint the difference between e.g. pretix 1.6 and 1.7, but it might take more effort to fingerprint a security release like 1.6.2 vs 1.6.1.

Of course, the correct fis is to have users update as soon as possible. That's why we introduced [automatic update checks](https://pretix.eu/about/en/blog/20170401-release-120/) in 1.2.0. But thats also where I get the (anonymous!) data from that says that there are quite some unupdated instances around…
