### ISSUE TITLE
Dashboard and event list in event timezones

### ISSUE THREAD

**Issue by Speedy1991** [pretix/pretix#648]
The datetime in dashboard is utc.
This is programmatically correct but kinda confusing for my admin colleagues.
They create an event with an timezone and put the "correct" datetime in their timezone but see an utc time on the dashboard.
Maybe it is a good idea to put two time information on the overview menu:
- UTC (as now)
- Timezone based (based on the timezone which was selected on the product)
e.g.:
![Example](http://fs5.directupload.net/images/171022/rpon6z8i.png)

**Comment by Speedy1991** [comment]
I think this is kinda easy to implement, here is some pseudocode:

https://github.com/pretix/pretix/blob/master/src/pretix/control/views/dashboards.py#L355
```
widgets.append({
    ...
    'tz': tz
})
```

https://github.com/pretix/pretix/blob/master/src/pretix/control/views/dashboards.py#L285
```
<div class="name">{event}</div>
<div class="row">
    UTC <div class="daterange">{daterange}</div>
    <div class="times">{times}</div>
</div>
<div class=row">
    {% timezone w.tz %}
    {{ w.tz }} <div class="daterange">{daterange}</div>
    <div class="times">{times}</div>
    {% endtimezone %}
</div>```

If you are interested i will create a PR

**Comment by raphaelm** [comment]
Thanks for the feedback! I think showing two dates is to complicated. With the next pretix release, you'll be able to set a timezone in your user profile that will be used for the dashboard and likewise "global" views. The dashboard should either always show user timezone or always show the timezone of the respective event (and I think user timezone is clearer).

**Comment by Speedy1991** [comment]
Thanks for the information. But what about this scenario:
User sets timezone Berlin(+1), creates an event in China (+8) at 2 pm china time.
What does the dashboard display? If it is the users timezone, it will be 2 pm - 8h (china) + 1h (berlin) = 7 am??
I think it would be better displaying the time related to the timezone of the event, not related to the users timezone.

**Comment by Speedy1991** [comment]
Another thought: maybe a setting in the pretix.cnf would be useful, something like:
```
[pretix]
dashboard_tz=[utc|user_timezone|event_timezone]
```

**Comment by raphaelm** [comment]
> I think it would be a better solution to display the time related to the timezone of the event, not related to the users timezone.

Probably, yes. It is easy to fix this for the dashboard. It is a bit less easy to fix it for the list of events since ordering by datetimes in different timezones is … well… hardly well-defined, but we could still do it.

But pretix' next version (at least the Enterprise edition) will have options to create reports that span multiple events and aggregations with different timezones will get to confusing.

So I think I'd merge something that makes it use event timezone for the dashboard and event list, but I'm not yet really sure it's the best approach.

To be fair, for most users it won't matter because their user timezone and the timezone of all their events can be the same.

> Another thought: maybe a setting in the pretix.cfg would be useful, something like:

No, I don't think more global settings are the solution. If more settings, then on user-level, but probably not even that.

**Comment by raphaelm** [comment]
I belive this is fixed by now.
