### ISSUE TITLE
[Feature Request] Better way getting the name for non invoice

### ISSUE THREAD

**Issue by Speedy1991** [pretix/pretix#694]
I need the name of the people ordering a ticket with "Require attendee names" in Settings -> General. But i can't see the name in the Orders -> All orders like i can if i check "Require Customer Name " in Invoicing.

Is it possible to add the name to the all orders if "Require Customer Name" is set and no invoice "Require Customer Name" is set?

The current problem is:
- Someone is paying with bank transfer and miss the Reference code.
At the moment there is only a mapping from email to the name of the bank transfer name, what is kinda hard if someone has a email e.g.: spacedragon@anything.com and this is Max Mustermann.

I also don't want to enable alwys Require Customer Name because the whole form with street, postal, etc is showing and not only the name field.

If u see my problem and want a PR i can provide one.

**Comment by raphaelm** [comment]
There is a very simple reason why the list of orders does not show attendee names: An order can contain any number of tickets and therefore any number of different attendee names. Attendee names are per ticket, customer names are per order. Showing potentially tens of names per row in the list of orders won't make it easier.

However, the search field in the orders list, the autocompletion during bank transfer assignment, and the global order search do take attendee names into account when searching, so this might help already?

We've had a special "All attendees" list before but dropped it again because it feels redundant to the check-in lists (that will improve further in 1.10). The check-in lists, however, only show paid orders so they don't help here.

**Comment by Speedy1991** [comment]
Ah i didn't know this option.
Thank you!
