### ISSUE TITLE
Expand spell-check to translation files

### ISSUE THREAD

**Issue by koebi** [pretix/pretix#707]
In [this commit](https://github.com/pretix/pretix/commit/9ab39904e851cbb228eaa53960ce330803b4f0ef), automatic spell-checking for the documentation is implemented. This spell-checking should now be expanded to the translation files in the [locale-directory](https://github.com/pretix/pretix/tree/master/src/pretix/locale).

So far, I have not found a convenient way to simply pass the .po-files to the spinx-contrib-spellchecker. 
One could now either look to modify its source code to be able to do this, or look into other means of spell-checking, e.g. wrapping aspell or maybe [pospelcheck](https://github.com/holygeek/pospelchek) or something else :)

**Comment by raphaelm** [comment]
I'm not sure what the easiest way here is, either. pospelcheck looks nice, but I'm not sure about requiring perl for the development setup, although it wouldn't be a blocker since spellchecks are a very optional feature of the development setup.

We could also write a simple script [reading the PO file](https://polib.readthedocs.io/en/latest/quickstart.html#loading-existing-catalogs) and using [PyEnchant](https://pythonhosted.org/pyenchant/tutorial.html#checking-entire-blocks-of-text) for the spell check, which is basically what sphinxcontrib-spellcheck does.

We could even do this as a new python library to be useful not only for pretix. I'm not sure if we want to go down that rabbit hole as it *looks* easy, but might be quite complicated.

**Comment by koebi** [comment]
While pospelcheck seems to be nice for manually checking the .po-files, I think its interactivity makes it not that suitable for an automatic spell check. Therefore, I'd like to have a look at a python script that checks the .po-files. We'll see where that leads ;)

**Comment by koebi** [comment]
A first proof of concept is implemented in #715 :)
