### ISSUE TITLE
504 Gateway Timeout Error

### ISSUE THREAD

**Issue by flexwie** [pretix/pretix#716]
I set up Pretfix stricly according to the installation document on a new Ubuntu 16.04 machine but I can't get it to serve the website. Instead its giving me a 504.

The docker container is running, nginx is up and configured like described and the SSLcertificates are working. What could I have been missing?

**Comment by raphaelm** [comment]
Did this happen after a new install or on an existing install? Does logs/pretix.log in the data volume of the container contain anything of interest?

**Comment by flexwie** [comment]
The install is new and the log file is empty

**Comment by raphaelm** [comment]
Weird. Can you post the output of ``docker logs <containername>``?

**Comment by flexwie** [comment]
I copied the whole output into this gist: https://gist.github.com/flexwie/5e24c9357a625ee251cd4a5dae725ba5

**Comment by flexwie** [comment]
Figured out that it might be the missing mysql.sock?

**Comment by raphaelm** [comment]
Hmm, okay, while pretixtask crashes, pretixweb doesn't so you should at least get an error 500… But the log looks like your database server is not running / not reachable at ``/var/run/mysqld/mysqld.sock``? Do you have MySQL running and is it listening via socket and is the socket correctly mounted into the docker container and has appropriate permissions?

**Comment by flexwie** [comment]
I got rid of the mySQL problem, by creating a swap file as I seemed to run out of memory.
I'm still getting a 504 error when accessing the page...
Docker log seems fine, nginx is only showing the time outs.

**Comment by raphaelm** [comment]
Since there now have been two reports of problems with the docker installation (#705 and #716), I created a shell script that closely follows the tutorial and executed it in a fresh virtual machine with debian stretch installed. I was thereby able to verify that the tutorial is correct and the resulting pretix instance was working for me. You can follow my steps and compare with your setup here: https://github.com/pretix/pretix-test-tutorials/blob/master/docker_smallscale/install.sh

Therefore, it appears to me that this problem is without the scope of the tutorial or the pretix software and somehow related to your server setup.

I found one bug during this procedure, the template ``/etc/systemd/system/pretix.service`` did only specify the docker container to be started as ``pretix/standalone``, not ``pretix/standalone:stable`` which *might* have caused that you run off the current git master instead of the stable version. Since I do not recommend downgrades, I suggest to stick with that until 1.11 comes out and then change this line to ``pretix/standalone:stable``. This shouldn't cause the problem reported here, though, since we also run the git master in production.

**Comment by raphaelm** [comment]
Maybe 1.10.1 fixes this problem as well. Make sure to read the notes on docker installations at the end of the blogpost:
https://pretix.eu/about/de/blog/20171216-release-1101/
