### ISSUE TITLE
Purchaser Authentication

### ISSUE THREAD

**Issue by cjol** [pretix/pretix#722]
I need to sell tickets to a closed community. No one outside this community should be able to purchase tickets. Vouchers could be a solution for this, but it's clunky and they can be shared outside the community.

Instead, I would like to force registration/login before tickets can be purchased. This opens up a few possibilities:
- different user "types" who would have access to different products or prices (sort of like an implicit voucher for certain users)
- secured ticket details, so no one else can change the answers to ticket questions
- cross-order ticket limits, so that a user can only buy e.g. 1 ticket no matter how many orders he places. 

Are any of these things currently possible? I think not but would love to be proven wrong. If I were to go about implementing this myself, what would be the best place to start?

**Comment by raphaelm** [comment]
Hi, 

thank you for your suggestion :)

This is currently not possible and will not be implemented in pretix. We had a complex concept of purchaser registration/login in pretix early on and completely removed it in 2015 because it was a big usability issue and did not add much value, so I don't see that it is coming back to pretix core.

Some of this can be done with vouchers, yes, but you listed the disadvantages yourself.

Some of this could be implemented by a [plugin](https://docs.pretix.eu/en/latest/development/api/plugins.html). The [checkout flow architecture](https://github.com/pretix/pretix/blob/master/src/pretix/presale/checkoutflow.py) allows plugins to register their own steps into the checkout process, which would enable you to embed a login step, although this would be after the  product selection. The [validate_cart](https://docs.pretix.eu/en/latest/development/api/general.html#pretix.base.signals.validate_cart) signal allows you to reject certain products to custom criteria (could be used to enforce cross-order limites, maybe). I believe it is possible, but certainly not trivial.

Some day there will also be an API to create orders (#599) which would allow you to run your own frontend that enforces your constraints, but have pretix handling all the background staff, but I fear that this is still quite some time in the future.

Best
Raphael
