### ISSUE TITLE
order_free email send with non-free payment provider

### ISSUE THREAD

**Issue by felixrindt** [pretix/pretix#751]
When only buying free products, pretix skips the payment checkout step and uses the `FreePaymentProvider` (identifier `free`). It then sends the email `event.settings.mail_text_order_free`. So far so good.

What if someone (read "I") is using a payment provider with `-100%` payment fee?  
(e.g. if one is a member of a club, they get in for free)  
When the customer has a cart with value > 0, you can select a payment provider. If that payment provider reduces your order total to 0, inconsistencies show:

- On the order confirmation page, the customer sees the text defined by the chosen payment provider
- The email template used is `event.settings.mail_text_order_free`, stating something else than the potential payment provider wants the user to know (e.g. "please confirm their club membership")

What I would expect, is that the email is also of type `event.settings.mail_text_order_placed` in which the payment provider can insert information, just like every normal payment mail. 

To do that, I think only this line should be changed to check the payment method, not order total:
https://github.com/pretix/pretix/blob/d622f38e1da6a98935c2c8720685fdee9cde85f1/src/pretix/base/services/orders.py#L516

Also, are there any problems with negative product prices and order totals?

**Comment by felixrindt** [comment]
I'm working on writing a PR, including a regression test...

**Comment by raphaelm** [comment]
> What if someone (read "I") is using a payment provider with -100% payment fee?

Then, that someone, is kind-of abusing the payment provider system, as we discussed in person 😉 I believe in this case vouchers or separate products (and then maybe payment providers limited to certain products etc.) should be used, but I do understand your reasons and if it is really solvable by an easy change, I think we'll do the change.

> To do that, I think only this line should be changed to check the payment method, not order total:

I think we can do that change. I'm a bit reluctant since checking for the payment provider here feels less "robust",  but since in the end it is only about the log and email text, there is only so much damage to be caused here.

This will solve your email inconsistency, but I fear you'll run into harder-to-solve problems in other places as well, for example when it comes to changing orders (e.g. changing the payment provider later or changing the order's content as an admin). I haven't looked at it in detail, though.

> Also, are there any problems with negative product prices and order totals?

Negative product prices *should be* fine, I never tested it. Negative order totals are certainly unknown territory and not officially supported ;)

**Comment by felixrindt** [comment]
After discussing this, we came to some conclusions:

- Changing pretix is fine, as long as existing supported behavior is not affected
- Not only should the correct email be send, but the order's status and payment provider should not change through adding or removingn products using the admin interface. For this, some more things in [orders.py](https://github.com/pretix/pretix/blob/master/src/pretix/base/services/orders.py) need to be modified.
- Vouchers can't accomodate for the behavior we get from a payment provider. Having multiple products would increase work on administration and coding and add confusion.

I'll work on said changes.
