### ISSUE TITLE
External authentication (LDAP, OAuth)

### ISSUE THREAD

**Issue by MaicoTimmerman** [pretix/pretix#775]
We'd like to use pretix in our current system, however we would like to share credentials between our main system and pretix, such that we do not have to create separate organization accounts for all our users in our organisation.

For example, we could implement the OAuth2 Password grant. Where we allow the user to login using their username and password, which pretix will check against the OAuth2 server to validity and create a local user.

**Comment by raphaelm** [comment]
I see why this would be useful. However, it wouldn't save you from creating organization accounts and them assigning teams and permissions to the users, am I right?

**Comment by MaicoTimmerman** [comment]
The important note there is, we are not dealing with user credentials and secrets. For permissions we could assign them manually or create some push/pull method.

**Comment by thegcat** [comment]
We'd be interested by LDAP authentication, so I guess this would somehow fit in a system for authentication? I have also quickly browsed the plugins section but it seems authentication plugins are currently not possible. Maybe this could be a solution?

**Comment by raphaelm** [comment]
We've had someone else request this a while back, so I've already given this some thought.

## The technical side

Django has [pluggable auth](https://docs.djangoproject.com/en/2.0/topics/auth/customizing/), but since we do some auth-related things, there's still quite a lot to change in pretix.

* pretix would need to grow the ability to work with external authentication. This means at minimum
** extending the User model by a source that the user data is coming from and that this user authenticates against
** extending the administrative views concerned with user management such that they now about external authentication (i.e. show details, hide password fields, ...)
** extending all authentication-related views to be compatible with external auth backends
** defining, documenting and implementing an interface that bridges between Django's authentication API and pretix' plugin system
* For LDAP specifically, [django-auth-ldap](https://django-auth-ldap.readthedocs.io/en/latest/) seems a decent implementation. However, to create a "pretix-ldap" plugin, one would still to 
** find a way to configure all the LDAP-related things in a way that is consistent with how pretix handles configuration in general
** create a datastructure and an editor that allows mapping LDAP groups to pretix teams
** build something that synchronizes LDAP group memberships with pretix team memberships e.g. on each login

## The business side

We do not have an interest in this ourselves currently, since this would probably be impossible to run on pretix Hosted and we haven't seen many customers interested so far. Besides academia, this is also a feature mostly relevant to customers who have good money to pay for it. 

Since none of us has LDAP knowledge to build on, we estimated that we can only build these features if we have customers committing to invest *at least* €2500 in this feature.

If someone would write a pull request, though, we'd gladly merge it (after a very critical review, because of the security-related nature of this). It shouldn't require a lot of knowledge of pretix in specific, general Django knowledge would suffice.

**Comment by thegcat** [comment]
Thanks for the feedback and insight.

To clarify what we are looking for: we are interested in the authentication part only, not the authorisation part, i.e. mapping LDAP groups to pretix teams is out of scope in our case.

I'm not a python person myself, but I'll see if anyone here would be interested in working on this and if the hints you gave above would already be enough to start something.

**Comment by raphaelm** [comment]
With #1447 it is now possible to implement custom authentication backends, so if someone wants to create a LDAP backend as a plugin, feel free! I suggest to use this issue to coordinate in case multiple people are interested in this.

Here's the documentation:
https://docs.pretix.eu/en/latest/development/api/auth.html
Let me know if there are unclear aspects.

**Comment by Sohalt** [comment]
I'll have a go at implementing LDAP authentication over the holidays if noone else wants to.

**Comment by Sohalt** [comment]
I've implemented LDAP authentication here: https://github.com/Sohalt/pretix-ldap.
I have not tested it extensively, so use on your own risk.

**Comment by raphaelm** [comment]
I think we can close this ticket now :)
