### ISSUE TITLE
Show ticket availability in (sub)event list

### ISSUE THREAD

**Issue by felixrindt** [pretix/pretix#785]
#### Situation
Imagine an event series with many dates of which many are sold out. A potential customer now needs to click through every subevent to find one which is not sold out (in the lists or calendar view).

![screenshot from 2018-02-23 18-11-07](https://user-images.githubusercontent.com/5970076/36607055-c6d27bfa-18c5-11e8-94ab-348bcd524857.png)![screenshot from 2018-02-23 18-23-28](https://user-images.githubusercontent.com/5970076/36607355-b0bd03fc-18c6-11e8-8bac-0507dac228f8.png)

That's not only tedious for the customer but might also lower conversion rate.

#### What to do?

This is not an easy question, since it's hard to decide when an event is considered 'sold out'.
I could imagine summing the availability of all products that provide admission for the event. If that sum is zero, the event could be considered sold out, although stuff like merchandise could still be available. Also we wouldn't want customers to not discover the waiting list.

Here's a mockup: ![screenshot from 2018-02-23 18-22-21](https://user-images.githubusercontent.com/5970076/36607314-85352228-18c6-11e8-923c-d0e647f47149.png)
Maybe yellow would be a better color?

What do you think about this? What would be a good way to implement this?

**Comment by rixx** [comment]
Great idea, that'd definitely be good to have, UX wise.

In minor niggle comments: I'd prefer labels of "Tickets on sale", "Waiting list available" "Sold out" ein green, orange, and red respectively (since as you said, we wouldn't want people to overlook an active waiting list).

**Comment by raphaelm** [comment]
I totally want this, ever since we have the calendar or list view and it is also something requested by some customers. Not only for subevents, but also for the organizer-level list of events. I've given this some thought already and I did not implement it yet for the following reasons:

For every event, we need to determine the available products. As you suggested, we might or might not want to restrict us to admission products. This is one (simple-ish) query as we need to take into account availability constraints (e.g. by time), etc. For every item, we need to get the quotas that affect this item. For every quota, we need to determine the current availability. This requires counting all affecting orders, cart positions, waiting list entries and vouchers, leading to 5 complex and slow database queries **per quota**.

Now take into account that I've seen conferences with up to 53 quotas. Loading the event dashboard of these events currently takes 1–2 seconds on the pretix.eu production infrastructure. On the other hand, I know of an organizer who uses pretix for 37 events next month alone (which would be the number of events to show in the calendar view).

Obviously, those are edge cases and usually, the organizers who use *lots* of quotas and the organizers who do *lots* of events are quite different kinds of people and also, of those >50 quotas usually only 2 or 3 relate directly to "real" admission products, the others relate to workshops that can be added as add-ons.

However, this does not take away my concern that this will be terribly slow.

Caching solves this only very superficially. For the event index page we cache quota availability for 5 seconds in order to survive high peak load. Caching for much longer would lead to confusion (i.e. once it is sold out it wouldn't start to show the waiting list link immediately). Also, when the cache is not filled, the first request in some time will always be slow no matter how much we cache. Caching "forever" with proper invalidation is hard to impossible since quota can change without any code being executed, e.g. when a cart expires.

For the list of events in the backend, we take a rather crude approach to quota caching which updates with every quota calculation (except if it has been updated in the last two minutes) and then periodically updates in a cronjob with a crude heuristic. This will still lead to outdated numbers in some edge cases and for that reason we display the calculation date/time next to the number. This is something we can get away with for the event organizers -- but not something suitable for end users.

I do not yet see how we could overcome these performance concerns. Of course, improving the UX is probably a bit more important than handling every edge case -- but I don't want it to collapse (or slow down everyone else!) in that edge case either.

**Comment by rixx** [comment]
I appreciate the complexity of calculating those quotas, thank you for the detailed write-up. :star2: 

I don't agree that crude caching is an issue here. While I agree that on the actual shop page of a single event we should never show something as available when it isn't, I don't think the same applies to overview pages such as calendars, sub-event lists etc. Having their status five minutes out of date would, to me, be vastly preferable to having no status at all.

**Comment by raphaelm** [comment]
> Having their status five minutes out of date would, to me, be vastly preferable to having no status at all.

Showing "sold out" while tickets are in fact available would be a major source of frustration, I guess (way more than the other way round, at least).

**Comment by felixrindt** [comment]
Again, thanks for your thoughts and comments. 
what about something like this:

![screenshot from 2018-02-25 22-37-30](https://user-images.githubusercontent.com/5970076/36646776-8f616010-1a7c-11e8-8076-6615db0dbbb5.png)

Would this be helpful for a user? Since tickets might become available again anyway (e.g. if a cart runs out), having a long cache time might be problematic. This on the other hand, is a very ambiguous statement. I'm not quite happy with it :/

On the other hand, since displaying remaining ticket availability in the event index can be turned on and off, couldn't this also be made opt-in/opt-out? 
This would put organizers in control about
* how calculating ticket availibility would affect performance and
* what effect a 'sold out' batch would have in the context of their event.

**Comment by raphaelm** [comment]
No update yet, sorry, with refactoring the payment framework completely and building a box office app, I've got too much on my plate right now :(

**Comment by felixrindt** [comment]
Yea I saw that! Really glad to see pretix mature. Drop a line if I can help you with testing or so :smile:

**Comment by raphaelm** [comment]
I just created PR #1112 with the following proposed design decisions.

> Showing "sold out" while tickets are in fact available would be a major source of frustration, I guess (way more than the other way round, at least).

Our *primary* users are event organizers, and they want to sell as many tickets as possible, so if we do any caching, we should lean towards showing "on sale", since that will make people click and buy. Showing "sold out" wrongly is more likely to scare away buyers, so we should avoid that. I changed the cache refreshing pattern in this direction. There's still some uncertainty with carts running out. I don't think "only few left" is a good-enough solution to this.

I decided to count all products, not only admission products, to avoid showing "sold out"/"unavailable" for events who actually only sell non-admission products. Not sure if this is the right decision, but since "admission products" have shown to be a concept that barely any user understands in the first placee, it's probably better this way.
