### ISSUE TITLE
Add more details to the order overview

### ISSUE THREAD

**Issue by abrock** [pretix/pretix#79]
After each and every number currently being showin in the order overview there could be the corresponding amount of money displayed, e.g.:

    Bambini (Youth ticket)        10 (133,70€)        1 (13,37€)     ..........

**Comment by abrock** [comment]
Also, the totals of the sub-categories could be bold too, not only the totals of the two categories (Tickets and Merch).

Perhaps make the totals for tickets and merch bold and a larger font size and the totals of the subcategories just bold.

**Comment by raphaelm** [comment]
I pushed a change for the money sums. In order to keep information density sensible on smaller displays, you can now toggle between the number of sales and the monetary volume.

I'm unsure about the bold product lines. You are right that it is a problem the way it is now, but I haven't yet found a solution that makes me completely happy.
The problem with making the "T-Shirt" line bold is, that "S", "M" etc. are only *variants* of the product "T-Shirt" -- so if an event does not make use of the *product variant* feature, the *whole* table would be bold. I'd rather make the variants smaller/italic/…
