### ISSUE TITLE
Add configurable minimum/maximum amount for payment methods

### ISSUE THREAD

**Issue by Janfred** [pretix/pretix#815]
It might be a wish of conference organizers to offer specific payment methods only, if the order exceeds a specific amount (e.g. due to static fees per order)

Maybe you also want to disable some payment methods if the total amount of the order exceeds another specific amount (e.g. cash payment if you don't want to have a huge amount of cash money at the entrance)

**Comment by raphaelm** [comment]
>  There are actually lots of useful criteria one could implement to show a payment provider or not.
> Next to available until there could also be available from. Showing some payment methods only to business costumers might be useful etc...

Yes. Most often requested is selection by product.

> Another option would be to create a new signal for plugins to add setting fields to the base payment provider and a signal for plugins to allow a payment method (like cart validation).

This sounds like it's getting easily out of control and nobody understands the result, but I don't have another idea right now :(

**Comment by raphaelm** [comment]
We've been now collecting requests for this feature over quite some time. If we don't count Felix' very special needs (sorry!), we're left with two requests

1. Enable/disable payment methods based on certain product selection
2. Enable/disable payment methods based on minimum/maximum amount

When we recently discussed this with a customer asking for 1, it turned out that they were in fact wanting to have 2, just haven't thought of it. There are two other problems with 1:

* 1 will lead to a complex UI, since for most use cases I can think of you require *both* "Enable only when XXX is in cart" and "Disable when YYY is in cart" (alternatively: "Enable only when XXX is in cart and nothing else"), but you don't get away with only one setting.
* Implementing 1 requires either new database models or a reference from the settings store to the database, which is always better avoided, this makes it not very nice to implement.

I will therefore, probably, implement (2) as it is suggested here.
