### ISSUE TITLE
Attendee Name / Ticket Holder

### ISSUE THREAD

**Issue by Duncanio** [pretix/pretix#822]
This feels pedantic but I'd rather bring it to your attention than not.

In the case where you have a mixture of individual tickets and family tickets the use of Attendee Name could become confusing as a Family Ticket may include 4 people but there is only one field (and one ticket).

Would Ticket Holder would be a more all encompassing label?

**Comment by raphaelm** [comment]
Well, the family ticket will also only reduce the quota by one and not four. Using a single ticket for four persons is certainly not an intended use case, even if there currently is no proper support for group tickets, I'm sorry.

**Comment by Duncanio** [comment]
Yes, fair enough.  In our case we are selling drive in movie tickets, our quota is per car.  We have variations of 1 Car 2 people, 1 Car 3 People etc. So in this case the quota would be correct.  Anyway, I understand completely what you are saying. Cheers.

**Comment by raphaelm** [comment]
Right, this is really an interesting edge case, I admit it :D

**Comment by StevenDeRoover** [comment]
In my case, there will be tickets given to children (children's party), so "Attendee name" is quite strange, as I would love it to be "Child's name".

I could try and make a seperate language for this, where "Attendee name" is translated into "Child's name", but that would be a big step in order to just label a question in an order.

As the "Attendee name" is already a "system question", listed in the Questions list of a product, wouldn't it be helpfull to change the label there, just like other custom questions?

Another path I followed was to disable the "system" name (Attendee name), and to create a custom question "Child's name", but that  answer cannot be used in the check-in process.

That could also be a possible option, if the first options in unavailable (changing the label): for custom questions to have a checkbox stating: "This is the name of the ticket holder".  By default, it would be the system question, of course.

**Comment by raphaelm** [comment]
We might allow more flexibility for system questions in the future, but it's not a priority at the moment
