### ISSUE TITLE
Making only the date for an event obligatory (and the time optional)

### ISSUE THREAD

**Issue by Problemkerze** [pretix/pretix#851]
Specifying a time is not always useful for the start and end of an event, so there should be an option to remove it.
Examples are conferences, exhibitions or tent camps lasting several days. Also events with a not clearly defined start or end (e.g. because the organizer offers optional travel or follow-up events can be booked).

**Comment by raphaelm** [comment]
We do need the time to be set, otherwise e.g. sorting operations in the list of events are not well-defined.

However, there already is the "Show dates with time" flag in the event settings that should remove the time from every *customer-facing* place. If you set this flag and the time is still shown to a user, please report it as a bug :)

**Comment by Problemkerze** [comment]
Whoops, thanks!
