### ISSUE TITLE
Stripe: Readable Description in customer's bank statement

### ISSUE THREAD

**Issue by Problemkerze** [pretix/pretix#852]
Provide an ID when paying with Credit Card (and other Stripe methods maybe) which relates to event and invoice.

It would be important to the customer to deliver him information like the event name, invoice number so he can associate his payment with the event (maybe also company and name for the settlement with his employer).
At the moment, the ID is something like ch_1CCmcbJI4vvpHOElRow0bTyD, generated by Stripe. Some additional information is delivered in the metadata which are not transferred to the customer and do not appear on the invoice.

**Comment by raphaelm** [comment]
I'm not sure what you are looking for.
We need to differentiate a few things here.

1. ``ch_1CCmcbJI4vvpHOElRow0bTyD`` is a charge ID, which is always generated by Stripe. We cannot modify it. It is not shown to the customer anywhere. We store in in pretix and show it to the organizer in order to be able to match pretix orders to Stripe payments.
2. We send the order code as "metadata", which is shown in the Stripe dashboard to the organizer in order to be able to match Stripe payments to pretix orders.
3. Customers do not see any payment-related IDs on their order page or in their invoice and I do not see what ID could be useful to them there.
4. There is the "statement descriptor", which is what users see on their own bank statement. For all Stripe methods except credit card, we currently set it to "EVENTSLUG-ORDERCODE". For credit cards, we currently don't and I'm not sure why, yielding the text from Stripe's business settings to appear. Is that what you are asking for?

**Comment by Problemkerze** [comment]
Charge ID: Yes, I was wrong. I was looking for the text which appears on the customer's bank statement.

Regarding the Invoice: Mentioning the payment method (and maybe the last 4 digits of the credit card) could be of relevance to customers from larger companies which are trying to get their money back from the accounting department.

Ad 4: I meant something like this. But there should be a direct relation between invoice and payment, comprehensible for the customer. 
In my eyes, either the invoice number should appear on the customer's bank statement or the invoice should state something like "The following debit order description will appear on your bank / credit card statement: EVENTSLUG-ORDERCODE"

**Comment by raphaelm** [comment]
> In my eyes, either the invoice number should appear on the customer's bank statement or the invoice should state something like "The following debit order description will appear on your bank / credit card statement: EVENTSLUG-ORDERCODE"

Sounds resonable.
