### ISSUE TITLE
Blacklisting

### ISSUE THREAD

**Issue by Problemkerze** [pretix/pretix#859]
Last year, we had some attendees who got drunk and rioted a little bit. We don't want them to come back. What about a black list for these fellows?

**Comment by felixrindt** [comment]
What would be on that list? They could create a new email, use a different address and even a fake name. How would Pretix identify these people?

**Comment by raphaelm** [comment]
I share Felix' scepticism. You can basically

1) Reject their registrations right away when they input their data, which will lead to them inputting false/other data
2) Reject their registrations later, which leads to additional effort since you might already have received money etc.

Solving social problems with technology rarely works. I'd recommend issuing a house ban (Hausverbot) and make clear in your Terms And Conditions that you can reject ticket registrations in such cases, with or without refund.

**Comment by Problemkerze** [comment]
Yes, this may be the easiest way to handle these issues, especially when taking into account that people can put in any data to register. 
Still - it could be interesting to have a measure to prevent "us" to enter a contract / to have any financial transaction in the first place.
But I guess the energy put into such a function would bear no relation to the little benefit.
