### ISSUE TITLE
Ticket download buttons/message should only be shown when ticket output providers are anabled

### ISSUE THREAD

**Issue by rimi-itk** [pretix/pretix#908]
When ticket download is enabled for an event and no ticket output providers are enabled, the order details page will show a message like

```
You will be able to download your tickets here starting on .
```

This message should only be shown when ticket output providers are enabled.

(In the example above, the “Ticket download date” is not set which makes the message look weird).

**Comment by raphaelm** [comment]
Hmm, no, I disagree. This message **deliberately** shows up when no output providers are (yet) enabled. There are reasons for some events to enable them only a few days/weeks before the event while selling tickets much earlier, which is exactly what the message says.
If you don't want to use the feature at all, you can disable this alltogether.

This does not yet explain why you see "starting on .", since that message is contained in a if statement with ``elif ticket_download_date``, so it should only show when a date is set.

**Comment by rimi-itk** [comment]
The ”starting on .” message is guarded by `not download_buttons` (cf. https://github.com/pretix/pretix/blob/master/src/pretix/presale/templates/pretixpresale/event/order.html#L94), but – as you hint – it should probably be `ticket_download_date` to avoid the display error.

When no ticket output providers are enabled, the user will never be able to download the tickets (making the message misleading), and if I understand the “Ticket download > Download date“ setting (https://docs.pretix.eu/en/latest/user/events/tickets.html) correctly, then it should be used to control when the user is allowed to download tickets (rather than enabling output providers at a later time).

**Comment by raphaelm** [comment]
> The ”starting on .” message is guarded by not download_buttons (cf. /src/pretix/presale/templates/pretixpresale/event/order.html@master#L94), but – as you hint – it should probably be ticket_download_date to avoid the display error.

Ah, I misread your patch there, sorry! So I think the line should read ``{% elif not download_buttons and ticket_download date %}``.

> When no ticket output providers are enabled, the user will never be able to download the tickets (making the message misleading), and if I understand the “Ticket download > Download date“ setting (docs.pretix.eu/en/latest/user/events/tickets.html) correctly, then it should be used to control when the user is allowed to download tickets (rather than enabling output providers at a later time).

Hmm, I see your point why the current solution is flawed, but your solution has a similar flaw: If I start selling tickets in June but only want to enable downloads in December, it might very well be that I'll want to use that time to install, configure and enable output providers and I haven't set that all up already when I sell my first ticket, but still want to show that message.

I think it's fine the way it is, because with setting that date a user clearly states that they want to give out tickets after all, I think we should respect that even if the user hasn't configured the providers yet. It stays a pitfall, though, I agree.

**Comment by rimi-itk** [comment]
I appreciate your comments and the reasons behind how it works. Our use of Pretix is a bit out of the ordinary and we'll work around this issue (for our use case).

Thanks.

**Comment by raphaelm** [comment]
Hmm, but if we fix the if clause and you just don't set a date, you should be all set, or do I miss something?

**Comment by rimi-itk** [comment]
Yes, a fix for the `elif` clause will work for us. I'll make a PR for this. Thanks.
