### ISSUE TITLE
Numeric reference code

### ISSUE THREAD

**Issue by fmorato** [pretix/pretix#915]
In Finland the banks expect the reference code to be numeric. Otherwise the fee for receiving payments increases dramatically: from 0.13€ to 0.55€ per payment in this specific case. Reference codes for international payments are prefixed by 'RF' (still not clear to me if it is a mandotory rule or best practice). The payment will fail if the reference code is not in this format and is only accepted if put in the message field.

I understand if this would not be a priority in the development process. How should I go about implementing this feature?

Reference links:

https://wiki.xmldation.com/support/fk/finnish_reference_number

https://uusi.op.fi/corporate-customers/payments-and-cash-management/invoicing-and-incoming-payments/referencecalculator

https://www.nordea.fi/en/business/our-services/accounts-payments/reference-numbers-calculator.html

**Comment by raphaelm** [comment]
Hmm.

I'm not inclined on changing the format of order codes in general, so what you'd need to do here is extending the bank transfer plugin by a database model that stores an additional "payment reference" for every order and then display that instead of the order code and use it for matching. Then pray that people actually read that and use it correctly ;)

I'm not yet sure I'd want to have that in core, but you could just develop an external plugin ("pretix-banktransfer-fi" or something like that) that "inherits" things from the core banktransfer plugin.

**Comment by fmorato** [comment]
Thanks for the reply :)

I'd expect at least the finnish people to use it correctly :)

How would I go about "inheriting" from the banktransfer plugin? Do I have to "fork" it or is there a way to just extend it? I was looking into Django docs for extending another app but had no success in making it work.

**Comment by raphaelm** [comment]
Sorry, I missed this notification.

> How would I go about "inheriting" from the banktransfer plugin? Do I have to "fork" it or is there a way to just extend it? I was looking into Django docs for extending another app but had no success in making it work.

There's no concept of inheriting/extending whole plugins, but you can create a new plugin and then make many of the building blocks inherit the building blocks of the existing plugin.

https://docs.pretix.eu/en/latest/development/api/payment.html

Example: The largest part of this is to implement a PaymentProvider class. This could for example inherit from the PaymentProvider class of the base plugin.

**Comment by fmorato** [comment]
Thanks. I made a simple plugin that solves my problem. :)

https://github.com/fmorato/pretix-banktransferfi
