### ISSUE TITLE
Not possible to import payments after deadline, even when "accept later payments" is active

### ISSUE THREAD

**Issue by Unicorn-rzl** [pretix/pretix#92]
It's not possible to accept new payments after the payment deadline even if the option "accept later payments" is active.
The interface states, that the payments could not be imported due to contingent limits.
Does the payment deadline somehow set the "left contingent" of products to zero?

**Comment by raphaelm** [comment]
Wil fix this today.

**Comment by raphaelm** [comment]
This is not a bug, but working as intended. See for example the help thext of the "Accept late payments" option:

> Accept payments that come after the end of the order's payment term. Payments will only be accepted if the regarding quotas have remaining capacity. No payments will be accepted after the 'Last date of payments' configured above.

The "last date of payments" option is ment to be used in a scenario, where (for example) no shirts should be paid for because they already have been printed.

If we would accept payments *later* than this last date of payments, then we would end up with paid orders that have not been considered. 

Therefore, in our case, it is the correct workaround to set this setting to a later date. It would not be correct to change the behaviour of the software, as this would lead to problems if someone with a failed credit-card payment completes his payment two days before our event.
