### ISSUE TITLE
Templates for Events

### ISSUE THREAD

**Issue by InnayTool** [pretix/pretix#944]
If you have very similar but not connected events, there should be a way to create them with a template.

**Comment by raphaelm** [comment]
Hi Yannick!

Thank you very much for your feedback and the suggestion. :)

Since it is already possible to copy all data from an existing event, you can just create an event that you call "template". I'm not sure a dedicated template feature would add anything worth the added complexity.

If anything is unclear, just let me know!

**Comment by InnayTool** [comment]
Thank you for quick reply. Works as I expect, very good. ;)
