### ISSUE TITLE
Send e-mail to attendees instead of order contacts

### ISSUE THREAD

**Issue by saschafoerster** [pretix/pretix#951]
Soweit ich das sehe, kann man nur die Besteller über Pretix mit E-Mails anschreiben. Es wäre schön, wenn man alle Teilnehmer vor einer Veranstaltung gesondert anschreiben könnte.

**Comment by raphaelm** [comment]
Yes, this is requested very often and I see the use case.

The main reason it isn't there already is that you *usually* want to have the link to the ticket order in all emails in order to make sure people know why they get that email and to allow them to get the ticket. However, the only currently existing link gives access to *all* tickets of that order,  not only the one of the attendee, which can be a problem. So we might want to create an "single-attendee ticket status page" first and I'm not yet sure it's worth the effort.

**Comment by rixx** [comment]
(For all non-German speaking participants: The original request was to be able to send emails to all *attendees* instead of all people who have bought the tickets.)

**Comment by raphaelm** [comment]
Fixed in #1299
