### ISSUE TITLE
Preventing user enumeration

### ISSUE THREAD

**Issue by bockstaller** [pretix/pretix#997]
It is currently possible to enumerate emails of team members using the password reset feature. The view should return in both cases (email known/unknown) the same message, to prevent this risk.

**Side effects:**
- No "There was an error sending the mail" exception for the user anymore. This information could be logged.
- No "We've already sent you an email in the last 24 hours." displayed to the user anymore.  
- Two new messages for the user. For example:  
"We have sent you an e-mail containing further instructions, if you own a valid account." (no redis instance available)
"We have sent you an e-mail containing further instructions, if you own a valid account. You can reset the password once every 24 hours. " (redis instance available)

If there are no objections, I would start implementing the described behaviour.

**Comment by raphaelm** [comment]
Hi,

sorry for the late reply, I was on vacation for a week.

First of all: if you find an issue in pretix that you think has security impact, please never report it publicly on GitHub, but privately to us at support@pretix.eu, so we can prepare a bugfix without giving the public to much notice that there's something going on here.

That said, since I see you already have created some commits, I'd be happy to see your PR!

Best
Raphael

**Comment by raphaelm** [comment]
Ah sorry, PR is already there ;)
