### ISSUE TITLE
Question: Definition of overpaid

### ISSUE THREAD

**Issue by felixrindt** [pretix/pretix#999]
It's me again with my 0 total pending orders. These are marked as overpaid, although they aren't really. 
![image](https://user-images.githubusercontent.com/5970076/44618922-84f8a200-a87f-11e8-86e8-6bb79c628dec.png)

It's these lines that are confusing me:
https://github.com/pretix/pretix/blob/35ddf6790e226aabc52441b1b06d42bcecfa7f6d/src/pretix/control/forms/filter.py#L280

Could you please explain the exact definition of overpaid to me, and in which case the last condition is needed?

**Comment by raphaelm** [comment]
Currently, the definition of overpaid is:

1. If the order status is **paid**, every order where the sum of payments minus the sum of refunds is larger than the order total.
2. If the order status is **canceled/expired**, every order where the sum of payments minus the sum of refunds is larger than zero.
3. If the order status is **pending/expired**, every order where the sum of payments minus the sum of refunds is equal or larger than the order total.

Case 1 and 2 are probably intuitive and we can all agree on them. Case 3 turns out to be a source of confusion and should probably be changed. When building this, I thought it was a great opportunity to call out orders with pending state even though no payment is missing (which shouldn't happen except for race conditions during payment), without taking the extra effort to give them a name. However, we should probably find another name for that.
